import 'main.dart';

final List<Item> allItems = [
  Item('iPhone 11 Pro Max Screen Original', 'SS-S16', 0),
  Item('iPhone 11 Pro Screen Original', 'SS-S15', 1),
  Item('iPhone 11 Screen Original', 'SS-S14', 0),
  Item('iPhone 12 Mini Screen Original', 'SS-S18', 0),
  Item('iPhone 12 Pro Max Screen Original', 'SS-S21', 0),
  Item('iPhone 12/12 Pro Screen Original', 'SS-S19', 0),
  Item('iPhone 13 Mini Screen Original', 'SP-IP13MS', 0),
  Item('iPhone 13 Pro Max Screen Original', 'SS-S24', 0),
  Item('iPhone 13 Pro Screen Original', 'SS-S23', 0),
  Item('iPhone 13 Screen Original', 'SS-S22', 0),
  Item('iPhone 14 Plus Screen High Copy', 'SP-IP14PS', 0),
  Item('iPhone 14 Plus Screen Original', 'SS-S26', 0),
  Item('iPhone 14 Pro Max Screen Original', 'SS-S28', 0),
  Item('iPhone 14 Pro Screen Original', 'SS-S27', 0),
  Item('iPhone 14 Screen Original', 'SS-S25', 0),
  Item('iPhone 16 Pro Max Original Screen', 'SP-OS16PM', 0),
  Item('iPhone 15 Pro Screen Original', 'SS-S30', 0),
  Item('iPhone 15 Screen Original', 'SS-S29', 0),
  Item('iPhone 16 Pro Screen Original', 'SP-IP16PS', 0),
  Item('iPhone 16 Screen Original', 'SP-IP16SO', 0),
  Item('iPhone 17 Pro Screen Original', 'SP-IP17PS', 0),
  Item('iPhone 6 Plus Screen Original', 'SS-S2', 0),
  Item('iPhone 6 Screen Original', 'SS-S1', 0),
  Item('iPhone 6S Plus Screen High Copy', 'SP-IP6SPS', 0),
  Item('iPhone 6S Plus Screen Original', 'SS-S4', 0),
  Item('iPhone 6S Screen Original', 'SS-S3', 0),
  Item('iPhone 7 Plus Screen Original', 'SS-S7', 0),
  Item('iPhone 7 Screen Height Copy', 'SP-IP7SHC', 0),
  Item('iPhone 7 Screen Original', 'SS-S6', 0),
  Item('iPhone 8 Plus Screen Hight Copy', 'SP-IP8PS', 0),
  Item('iPhone 8 Plus Screen Original', 'SS-S9', 0),
  Item('iPhone 8 Screen Original', 'SS-S8', 0),
  Item('iPhone SE "2nd Gen" Screen Original', 'SS-S17', 0),
  Item('iPhone X Screen Original', 'SS-S10', 0),
  Item('iPhone XR Screen Original', 'SS-S13', 0),
  Item('iPhone XS Max Screen Original', 'SS-S12', 0),
  Item('iPhone XS Screen Original', 'SS-S11', 0),
  Item('iPhone 15 Pro Max Screen Original', 'SS-S31', 0),
  Item('iPhone 15 Plus Original Screen', 'SP-15PS', 0),
  Item('Battery', '', 0),
  Item('iPhone 11 Battery Original', 'SS-B14', 1),
  Item('iPhone 11 Pro Battery Original', 'SS-B15', 2),
  Item('iPhone 11 Pro Max Battery Original', 'SS-B16', 1),
  Item('iPhone 12 Mini Battery Original', 'SS-B18', 0),
  Item('iPhone 12 Pro Max Battery Original', 'SS-B21', 1),
  Item('iPhone 12/12 Pro Battery Original', 'SS-B19', 0),
  Item('iPhone 13 Battery Original', 'SS-B22', 4),
  Item('iPhone 13 Mini Original Battery', 'SP-13MOB', 1),
  Item('iPhone 13 Pro Battery Original', 'SS-B23', 1),
  Item('iPhone 13 Pro Max Battery Original', 'SS-B24', 0),
  Item('iPhone 14 Original Battery', 'SP-OB14', 2),
  Item('iPhone 14 Plus Battery Original', 'SP-OB14P', 0),
  Item('iPhone 14 Pro Battery Original', 'SP-14P', 0),
  Item('iPhone 14 Pro Max Battery Original', 'SP-14PMB', 0),
  Item('iPhone 15 Battery Original', 'SP-IP15B', 1),
  Item('iPhone 15 Plus Battery Original', 'SP-IP15PB', 0),
  Item('iPhone 15 Pro Battery Original', 'SP-IP15PB', 0),
  Item('iPhone 15 Pro Max Battery Original', 'SP-IP15PMB', 1),
  Item('iPhone 16 Battery Original', 'SP-IP16B', 0),
  Item('iPhone 16 Pro Battery Original', 'SP-IP16PB', 0),
  Item('iPhone 16 Pro Max Battery Original', 'SP-IP16PMB', 0),
  Item('iPhone 6 Battery Original', 'SS-B1', 0),
  Item('iPhone 6 Plus Battery Original', 'SS-B2', 0),
  Item('iPhone 6S Battery Original', 'SS-B3', 0),
  Item('iPhone 6S Plus Battery Original', 'SS-B4', 0),
  Item('iPhone 7 Battery Original', 'SS-B6', 0),
  Item('iPhone 7 Plus Battery Original', 'SS-B7', 0),
  Item('iPhone 8 Battery Original', 'SS-B8', 0),
  Item('iPhone 8 Plus Battery Original', 'SS-B9', 0),
  Item('iPhone SE "1nd Gen" Battery Original', 'SP-OB!ST', 0),
  Item('iPhone SE "2nd Gen" Battery Original', 'SS-B17', 0),
  Item('iPhone X Battery Original', 'SS-B10', 1),
  Item('iPhone XR Battery Original', 'SS-B13', 0),
  Item('iPhone XS Battery Original', 'SS-B11', 1),
  Item('iPhone XS Max Battery Original', 'SS-B12', 0),
  Item('Google Pixel 7 pro  Battery', 'SP-GP7P', 0),
  Item('Ear Speaker', '', 0),
  Item('iPhone 13 Mini Original Ear Speaker', '', 0),
  Item('iPhone 11 Ear Speaker Original', 'SP-APPES', 0),
  Item('iPhone 11 Pro Ear Speaker Original', 'SS-M38', 0),
  Item('iPhone 11 Pro Max Ear Speaker Original', 'SS-M39', 0),
  Item('iPhone 12 Mini Ear Speaker Original', 'SS-M40', 0),
  Item('iPhone 12 Pro Max Ear Speaker Original', 'SS-M42', 0),
  Item('iPhone 12/12 Pro Ear Speaker Original', 'SS-M45', 1),
  Item('iPhone 13 Ear Speaker Original', 'SS-M43', 0),
  Item('iPhone 13 Pro Ear Speaker Original', 'SS-M46', 0),
  Item('iPhone 13 Pro Max Ear Speaker Original', 'SS-M47', 0),
  Item('IPhone 14 Original Ear Speaker', 'SS-M48', 0),
  Item('iPhone 6 Ear Speaker Original', 'SS-M105', 0),
  Item('iPhone 6 Plus Ear Speaker Original', 'SS-M25', 0),
  Item('iPhone 6S Ear Speaker Original', 'SS-M26', 0),
  Item('iPhone 6S Plus Ear Speaker Original', 'SS-M27', 0),
  Item('iPhone 7 Ear Speaker Original', 'SS-M28', 0),
  Item('iPhone 7 Plus Ear Speaker Original', 'SS-M30', 0),
  Item('iPhone 8 Ear Speaker Original', 'SS-M31', 0),
  Item('iPhone 8 Plus Ear Speaker Original', 'SS-M32', 0),
  Item('iPhone SE "2nd Gen" Ear Speaker Original', 'SS-M33', 0),
  Item('iPhone X Ear Speaker Original', 'SS-M41', 0),
  Item('iPhone XR Ear Speaker Original', 'SS-M34', 0),
  Item('iPhone XS Ear Speaker Original', 'SS-M37', 0),
  Item('iPhone XS Max Ear Speaker Original', 'SS-M35', 0),
  Item('Loud Speaker', '', 0),
  Item('iPhone 11 Loud Speaker Original', 'SS-M62', 0),
  Item('iPhone 11 Pro Loud Speaker Original', 'SS-M63', 0),
  Item('iPhone 11 Pro Max Loud Speaker Original', 'SS-M64', 0),
  Item('iPhone 12 Loud Speaker Original', 'SS-M67', 0),
  Item('iPhone 12 Mini Loud Speaker Original', 'SS-M66', 0),
  Item('iPhone 12 Pro Loud Speaker Original', 'SS-M68', 0),
  Item('iPhone 12 Pro Max Loud Speaker Original', 'SS-M69', 0),
  Item('iPhone 13 Loud Speaker Original', 'SS-M70', 0),
  Item('iPhone 13 Mini Loud Speaker Original', 'SP-IP13ML', 0),
  Item('iPhone 13 Pro Loud Speaker Original', 'SS-M71', 0),
  Item('iPhone 13 Pro Max Loud Speaker Original', 'SS-M72', 0),
  Item('iPhone 15 Pro Loud Speaker Original', 'SP-IP15PLS', 0),
  Item('iPhone 15 Pro Max Loud Speaker', 'SP-IP15PMLS', 0),
  Item('iPhone 16 Loud Speaker Original', 'SP-IP16S', 0),
  Item('iPhone 6 Loud Speaker Original', 'SS-M49', 0),
  Item('iPhone 6 Plus Loud Speaker Original', 'SS-M50', 0),
  Item('iPhone 6S Loud Speaker Original', 'SS-M51', 0),
  Item('iPhone 6S Plus Loud Speaker Original', 'SS-M52', 0),
  Item('iPhone 7 Loud Speaker Original', 'SS-M54', 0),
  Item('iPhone 7 Plus Loud Speaker Original', 'SS-M55', 0),
  Item('iPhone 8 Loud Speaker Original', 'SS-M56', 0),
  Item('iPhone 8 Plus Loud Speaker Original', 'SS-M57', 0),
  Item('iPhone SE "2nd Gen" Loud Speaker Original', 'SS-M65', 0),
  Item('iPhone X Loud Speaker Original', 'SS-M58', 0),
  Item('iPhone XR Loud Speaker Original', 'SS-M61', 0),
  Item('iPhone XS Loud Speaker Original', 'SS-M59', 0),
  Item('iPhone XS Max Loud Speaker Original', 'SS-M60', 0),
  Item('Charging Port', '', 0),
  Item('iPhone 11 Charging Port Original', 'SS-M14', 0),
  Item('iPhone 11 Pro Charging Port Original', 'SS-M15', 0),
  Item('iPhone 11 Pro Max Charging Port Original', 'SS-M16', 0),
  Item('iPhone 12 Mini Charging Port Original', 'SS-M18', 0),
  Item('iPhone 12 Pro Max Charging Port Original', 'SS-M21', 0),
  Item('iPhone 12/12 Pro Charging Port Original', 'SS-M19', 0),
  Item('iPhone 13 Charging Port Original', 'SS-M22', 0),
  Item('iPhone 13 Pro Charging Port Original', 'SS-M23', 0),
  Item('iPhone 13 Pro Max Charging Port Original', 'SS-M24', 0),
  Item('iPhone 14 Charging Port Original', 'CH-IP14CHP', 0),
  Item('iPhone 14 Plus Charging Port Original', 'SP-CHiP14S', 0),
  Item('iPhone 14 Pro Charging Port Original', 'SP-CHiP14P', 0),
  Item('iPhone 14 Pro Max Original Charging Port', 'SP-000CHP', 0),
  Item('iPhone 15 Charging Port Original', 'SP-IP15CHP', 0),
  Item('iPhone 15 Pro Charging Port Original', 'SP-IP15PCHH', 0),
  Item('iPhone 15 Pro Max Charging Port Original', 'SP-IP15PMCHP', 0),
  Item('iPhone 16 Charging Port Original', 'SP-IP16CH', 0),
  Item('iPhone 16 Pro Max Charging Port Original', 'SP-IP16PMCHP', 0),
  Item('iPhone 6 Charging Port Original', 'SS-M1', 0),
  Item('iPhone 6 Plus Charging Port Original', 'SS-M2', 0),
  Item('iPhone 6S Charging Port Original', 'SS-M3', 0),
  Item('iPhone 6S Plus Charging Port Original', 'SS-M4', 0),
  Item('iPhone 7 Charging Port Original', 'SS-M6', 0),
  Item('iPhone 7 Plus Charging Port Original', 'SS-M7', 0),
  Item('iPhone 8 Charging Port Original', 'SS-M8', 0),
  Item('iPhone 8 Plus Charging Port Original', 'SS-M9', 0),
  Item('iPhone SE "2nd Gen" Charging Port Original', 'SS-M17', 0),
  Item('iPhone X Charging Port Original', 'SS-M10', 0),
  Item('iPhone XR Charging Port Original', 'SS-M13', 0),
  Item('iPhone XS Charging Port Original', 'SS-M11', 0),
  Item('iPhone XS Max Charging Port Original', 'SS-M12', 0),
  Item('Back Camera', '', 0),
  Item('iPhone 11 Back Camera Original', 'SS-M86', 0),
  Item('iPhone 11 High Copy Back Camera Lens', 'SS-HCCL', 0),
  Item('iPhone 11 Pro Back Camera Lens Original', 'SP-IP11PBCL', 0),
  Item('iPhone 11 Pro Back Camera Original', 'SS-M87', 0),
  Item('iPhone 11 Pro Max Back Camera Original', 'SS-M88', 0),
  Item('iPhone 12 Back Camera Original', 'SS-M91', 0),
  Item('iPhone 12 Mini Back Camera Original', 'SS-M90', 0),
  Item('iPhone 12 Pro Back Camera Original', '', 0),
  Item('iPhone 12 Pro Max Back Camera Original', 'SS-M93', 0),
  Item('iPhone 12 Pro Max High Copy Back Camera Lens', 'BC-HC12', 0),
  Item('iPhone 12 Pro Max Original Back Camera Lens', 'SP-CL', 0),
  Item('iPhone 13 Back Camera Lens High Copy', 'BCL-iP13', 0),
  Item('iPhone 13 Back Camera Original', 'SS-M94', 0),
  Item('iPhone 13 Pro Back Camera Lens Original', 'SP-IP13PBC L', 3),
  Item('iPhone 13 Pro Back Camera Original', 'SS-M95', 0),
  Item('iPhone 13 Pro Max Back Camera Lens Original', 'SP-IP13PMCL', 0),
  Item('iPhone 13 Pro Max Back Camera Original', 'SS-M96', 0),
  Item('iPhone 14 Back Camera Original', 'SP-I14BC', 0),
  Item('iPhone 14 Plus Back Camera Original', 'SP-IP14PBCP', 0),
  Item('iPhone 14 Pro Back Camera Lens Original', 'SP-IP14PBC', 0),
  Item('iPhone 14 Pro Max Original Back Camera', 'SS-14PMBC', 0),
  Item('iPhone 14 Pro Original Back Camera', 'SP-IP14PBC', 0),
  Item('iPhone 15 Back Camera Original', 'SP-IP15BC', 0),
  Item('iPhone 15 Plus Back Camera Original', 'SP-IP15PBC', 0),
  Item('iPhone 15 Pro Max Back Camera Original', 'SP-IP15PMBC', 0),
  Item('iPhone 6 Back Camera Original', 'SS-M73', 0),
  Item('iPhone 6 Plus Back Camera Original', 'SS-M74', 0),
  Item('iPhone 6S Back Camera Original', 'SS-M75', 0),
  Item('iPhone 6S Plus Back Camera Original', 'SS-M76', 0),
  Item('iPhone 7 Back Camera Original', 'SS-M78', 0),
  Item('iPhone 7 Plus Back Camera Original', 'SS-M79', 0),
  Item('iPhone 8 Back Camera Original', 'SS-M80', 0),
  Item('iPhone 8 Plus Back Camera Original', 'SS-M81', 0),
  Item('iPhone SE "2nd Gen" Back Camera Original', 'SS-M89', 0),
  Item('iPhone X Back Camera Original', 'SS-M82', 0),
  Item('iPhone X High Copy Back Camera Lens', 'IP-XHC', 0),
  Item('iPhone XR Back Camera Lens', 'SP-IPXRBCL', 0),
  Item('iPhone XR Back Camera Original', 'SS-M85', 0),
  Item('iPhone XS Back Camera Original', 'SS-M83', 0),
  Item('iPhone XS Max Back Camera Original', 'SS-M84', 0),
  Item('iPhone14 Pro Max Back Camera Lens High Copy', 'SPHC-14PMCL', 0),
  Item('PS Stock', '', 0),
  Item('Service:PS Cleaning', 'SE-PSC', 0),
  Item('PlayStation / X-Box ALPS  Analog Original', 'SP-PSAA', 0),
  Item('PlayStation 4 Controller Conductive PS4B-P4 Original', 'SP-PS4P4', 0),
  Item('Projector Epson EBX49 Lumen XGA', 'EG-552632678', 0),
  Item('PS Touch Pad Flat Original', 'SP-PSTP', 0),
  Item('PS4 Control Button Sheet Original', 'SP-PS4CBS', 0),
  Item('PS4 Controller Flat  Short Original', 'SP-PS4CFS', 0),
  Item('PS4 Controller Flat Tall Original', 'SP-PS4CFT', 0),
  Item('PS4 Charging Port Original', 'SP-PS5CHP', 0),
  Item('PS5 Control Button Sheet Original', 'SP-PS5CBS', 0),
  Item('PS5 Dual Sense Wireless Controller Original', 'SP-PS5DSWC', 0),
  Item('PlayStation 4 Analog Cover Original', 'SP-PS4AC', 4),
  Item('PlayStation 4 Button Silicone Conductive Rubber', 'SP-PS4BR', 3),
  Item('PlayStation 4 CD Room', 'SP-PS4C', 0),
  Item('PlayStation 4 Controller  Charging Board Port  JDS 055 Original', 'SP-PS4JDS055', 0),
  Item('PlayStation 4 Controller  Charging Board Port  LED 2227 Original', 'SP-PS4LED2227', 0),
  Item('PlayStation 4 Controller  Charging Board Port D2 Original', 'SP-PS4D2', 0),
  Item('PlayStation 4 Controller  Charging Board Port JDS001 Original', 'SP-PS4JDS001', 0),
  Item('PlayStation 4 Controller  Charging Board Port JDS011 Original', 'SP-PS4JDS011', 0),
  Item('PlayStation 4 Controller  Charging Board Port JDS040 Original', 'SP-PSJD040', 0),
  Item('PlayStation 4 Controller  Charging Board Port JDS050 Original', 'SP-PS4050', 0),
  Item('PlayStation 4 Controller  Charging Board Port JDYD2312 Original', 'SP-PS42312', 0),
  Item('PlayStation 4 Controller  Charging Board Port JO5 Original', 'SP-PS4JO5', 0),
  Item('PlayStation 4 Controller Battery 1 Original', 'SP-PS4CB1', 2),
  Item('PlayStation 4 Controller Battery 2 Original', 'SP-PS4CB2', 0),
  Item('PlayStation 4 Controller Charging Board Port Fool V1 Original', 'SP-PS4CHP', 0),
  Item('PlayStation 4 Controller Charging Board Port H2437 Original', 'SP-PS4CH', 0),
  Item('PlayStation 4 Controller Conductive PS4B-P4 Original', 'SP-PS4P4', 0),
  Item('PlayStation 4 Controller Conductive Sheet 1619 Original', 'SP-PS4CC1619', 0),
  Item('PlayStation 4 Controller Conductive Sheet 1721 Original', 'SP-PS4CC1721', 0),
  Item('PlayStation 4 Controller Conductive Sheet 2133 Original', 'SP-PS4CC2133', 0),
  Item('PlayStation 4 Controller Conductive Sheet 2345 Original', 'SP-PS4CC2345', 0),
  Item('PlayStation 4 Controller Conductive Sheet 2348 Original', 'SP-PS4C2348', 0),
  Item('PlayStation 4 Controller Conductive Sheet 2418 Original', 'SP-PS4C2418', 0),
  Item('PlayStation 4 Hall Effect Magnetic Analog Original', 'SP-PS4HEFFMA', 3),
  Item('PlayStation 4 Sheet 1631 Original', 'SP-PS41631', 0),
  Item('PlayStation 4 Sheet 2246 Original', 'SP-PS42246', 0),
  Item('PlayStation 4 Sheet 2446 Original', 'SP-PS4SHEET', 0),
  Item('PlayStation 4&5 Controller flat 12 Original', 'SP-PS45CF12', 0),
  Item('PlayStation 4&5 Controller flat 14 Original', 'SP-PS45CF14', 0),
  Item('PlayStation / PS5 ALPS  Anal', '', 0),
  Item('PS 5 Analog Cover Original', 'SP-PS5AC', 3),
  Item('PS 5 Charging Port Original', 'SP-PSCH', 0),
  Item('PlayStation 5 Button Silicone Conductive Rubber', 'SP-PS5BR', 0),
  Item('PlayStation 5 Controller Battery Original', 'SP-PS5CB', 0),
  Item('PlayStation 5 Controller Charging Port Socket Original', 'SP-PS5C', 0),
  Item('PlayStation 5 Controller Conductive Sheet 1,2 Original', 'SP-PS5CC12', 1),
  Item('PlayStation 5 Controller Conductive Sheet 3 Original', 'SP-PS5CC3', 0),
  Item('PlayStation 5 Controller flat  Original', 'SP-PS5CF', 0),
  Item('PlayStation 5 Controller R-L FFC Flexible Flat Original', 'SP-PS5RL', 0),
  Item('PlayStation 5 Gen 3 Controller Flat Original', 'SP-PS5GEN', 0),
  Item('PlayStation 5 Hall Effect Magnetic Analog Original', 'SP-PS5AM', 5),
  Item('PlayStation 5 Housing Gen 3 Original', 'SP-PS5HG3', 0),
  Item('PlayStation 5 L2 R2 Original', 'SP-PS5L2R2O', 0),
  Item('PlayStation 5 Mic Flat Original', 'SP-PS5MF', 0),
  Item('PlayStation 5 V3 Middle frame Original', 'SP-PSMF', 0),
  Item('PlayStation HDMI Hardware', 'PS-SHDH', 0),
  Item('XBox L2 Button Original', 'SP-AL2B', 0),
  Item('XBox Cover Analog Original', 'SP-XAC', 3),
  Item('Xbox 1 Analoug Original', 'SP-XB1', 6),
  Item('X-Box 1 Button Silicone Conductive Rubber Original', 'SP-XB1BR', 0),
  Item('X-Box SE Socket Original', 'SP-XBSES', 0),
  Item('X-Box 360 Button Silicone Conductive Rubber Original', 'SP-XB360BR', 0),
  Item('X-Box 1 Sheet Original', 'SP-XB1S', 0),
  Item('MacBook Spare Part', '', 0),
  Item('MacBook 1 Piece Original Button', 'SP-1PB', 0),
  Item('MacBook A1278 Hard Disk Flat', 'MC-HD', 0),
  Item('MacBook A1278 Original Battery', 'SPMB-OBA1278', 0),
  Item('MacBook A1278 Original Keyboard', 'SPMB-OKB1278', 0),
  Item('MacBook A1286 Keyboard Original', 'SPMB-1286OKB', 0),
  Item('MacBook A1286 Original Battery', 'MB-A1286', 0),
  Item('MacBook A1398 Keyboard Original', 'SPMB-OKB1398', 0),
  Item('MacBook A1398 Original Battery', 'SPB-MBA1398', 0),
  Item('MacBook A1398 Original Loudspeaker', 'SP-MB1398LS', 0),
  Item('MacBook A1398 Original Screen', 'SPMB-OS1398', 0),
  Item('MacBook A1425 Battery Original', 'SP-MB1425B', 0),
  Item('MacBook A1425 Original Loud Speaker', 'SP-A1425LS', 0),
  Item('MacBook A1465 Keyboard Original', 'SOMB-OKB1465', 0),
  Item('MacBook A1465 Original Battery', 'SPMB-OB1465', 0),
  Item('Macbook A1466 Back Original', 'SP-MB1466B', 0),
  Item('MacBook A1466 Keyboard', '', 0),
  Item('MacBook A1466 Original Battery', 'MC-1466B', 0),
  Item('MacBook A1502 Ear Speaker Original', 'SP-MB1502ES', 0),
  Item('MacBook A1502 Motherboard Original', 'SP-MB1502MB', 0),
  Item('MacBook A1502 Original keyboard', '', 0),
  Item('MacBook A1502 Original loud Speaker', 'SP-MB1502LS', 0),
  Item('MacBook A1502 Original screen', '', 0),
  Item('MacBook A1534 Keyboard Original', 'SOMB-OKB1534', 0),
  Item('MacBook A1534 Original Battery', 'SP-A1534OB', 0),
  Item('MacBook A1534 Original Screen', 'SPMB-OS1534', 0),
  Item('MacBook A1706 Original Battery', 'SPA1706-MBOB', 0),
  Item('MacBook A1706 Original Keyboard', 'SP-KYA1706', 0),
  Item('MacBook A1706/A1708 Original Screen', 'SPMB-OS1706/1708', 0),
  Item('MacBook A1707 Keyboard Original', 'SPMB-OKB1707', 0),
  Item('MacBook A1707 Original Battery', 'SP-A1707OB', 0),
  Item('MacBook A1707 Original Button', 'SP-MB1707B', 0),
  Item('MacBook A1707 Original Screen', 'SPMB-OS1707', 0),
  Item('MacBook A1708 Original Battery', 'MB-O', 0),
  Item('MacBook A1708 Original Keyboard', 'SP-A1708', 0),
  Item('MacBook A1708 Original Screen', 'SP-A1708S', 0),
  Item('Macbook A1708 REF Device', 'REF-MB1708REF', 0),
  Item('MacBook A1932 Keyboard Original', 'SPMB-OKB1932', 0),
  Item('MacBook A1932 Original  Screen', 'SPMB-1932OS', 0),
  Item('MacBook A1932 Original Battery', 'SPMB-OB1932', 0),
  Item('MacBook A1989 Keyboard  Original', 'SP-MB1989KO', 0),
  Item('MacBook A1989 Original Battery', 'SPMB-OB1989', 0),
  Item('MacBook A1989 Original Motherboard', 'SP-A1989MB', 0),
  Item('MacBook A1989 Original Screen', 'SP-A1989OS', 0),
  Item('MacBook A1990 Keyboard Original', 'SPMB-OKB1990', 0),
  Item('MacBook A1990 Original Battery', 'SP-A1990B', 0),
  Item('MacBook A1990 Original Screen', 'SP-A1990S', 0),
  Item('MacBook A2141 Keyboard Original', 'SPMB-OKB2141', 0),
  Item('MacBook A2141 Original Battery', 'MB-SPOB', 0),
  Item('MacBook A2141 Original Motherboard', '', 0),
  Item('MacBook A2159 Keyboard Original', 'SPMB-OKB2159', 0),
  Item('MacBook A2159 Original Battery', 'SPMB-OB2159', 0),
  Item('MacBook A2159 Original Screen', 'SPMBOS-A2159', 0),
  Item('MacBook A2179 Keyboard Original', 'SPMB-OKB2179', 0),
  Item('MacBook A2179 Original Battery', '', 0),
  Item('MacBook A2179 Trackpad Original', 'SP-MB2179', 0),
  Item('MacBook A2251 Loud Speaker Original', 'SP-M2251', 0),
  Item('MacBook A2251 Original Screen', 'MB-OS', 0),
  Item('MacBook A2289 Original Screen', 'SPMB-OS2289', 0),
  Item('MacBook A2337 Keyboard Original', 'SPMB-OKB2337', 0),
  Item('MacBook A2337 Original Battery', 'SP-OBA2337', 0),
  Item('MacBook A2337 Original Screen', 'MB-A2337OS', 0),
  Item('MacBook A2338 Keyboard Original', 'SPMB-OKB2338', 0),
  Item('MacBook A2338 Original Battery', 'SPMB-OBA2338', 0),
  Item('MacBook A2338 Original Touch Bar', 'MBP-A2338', 0),
  Item('MacBook A2442 Battery Original', 'SP-MA22', 0),
  Item('MacBook A2442 Original Screen', 'SPMB-OS2442', 0),
  Item('MacBook A2485 Button Original', 'SP-MBA2485B', 0),
  Item('MacBook A2485 keyboard Original', 'SP-MB4', 0),
  Item('MacBook a2485 Screen Original', 'SP-MA2485S', 0),
  Item('MacBook A2681 Original Battery', 'SP-MB2681B', 0),
  Item('MacBook A2991 M3 Pro Screen Original', 'SP-MB2991MP', 0),
  Item('MacBook A3112 M4 Screen Original', 'SP-MB3122S', 0),
  Item('Macbook A3113 Trackpad', 'SP-M3113TP', 0),
  Item('MacBook Air A1466 Charging Port', 'SS-M100', 0),
  Item('MacBook Air A1466 Motherboard Original', 'SP-MB1466', 0),
  Item('MacBook Air A1466 Screen Replacement', '', 0),
  Item('MacBook Air A2179 Original Screen', 'SP-MBAS2179', 0),
  Item('MacBook Air M1 2337 Track Pad', 'SP-MBA1', 0),
  Item('MacBook Air M2 Screen Original', 'SP-MBAIR', 0),
  Item('MacBook Air1 A2337 Track Pad Flat', 'SP-MBA1TF', 0),
  Item('MacBook Button', 'SB-MCB', 0),
  Item('MacBook Hard Disk 512GB', '', 0),
  Item('MacBook Pro 16 A2141 Original Screen', 'MBP-16OS', 0),
  Item('MacBook Pro 2015 A1502 Battery', '', 0),
  Item('MacBook Pro A1466  Socket', 'SP-MP1466S', 0),
  Item('MacBook Pro A1502 Keyboard', 'MC-KY', 0),
  Item('MacBook Pro A1708 original screen', '', 0),
  Item('MacBook Pro A2338 Original Screen', 'MBP-A2338S', 0),
  Item('MacBook Pro M1 A2338 Original Battery', '', 0),
  Item('MacBook Pro M1 Battery Original', 'SP-MPM1B', 0),
  Item('MacBook Pro M1 Pro 16in Screen', 'MP-M1S', 0),
  Item('iPad Spare Part', '', 0),
  Item('iPad  Air4 Charging Port Original', 'SP-IDCHPA4', 0),
  Item('iPad 10.2 7/8/9 Original Housing', 'SP-7/8/9OH', 0),
  Item('iPad 10.2in 7/8/9 Gen Battery Original', '', 0),
  Item('iPad 10Gen 10.9 Original LCD', 'SP-iP10.9L', 0),
  Item('IPad 10Gen 10.9 Screen Original', 'SS-IP10', 0),
  Item('iPad 10Gen 10.9 Touch Panel', 'SP-iP10.9TP', 0),
  Item('iPad 11 Pro 1 Gen Charging Port', 'SP-ID11P1CP', 0),
  Item('iPad 12.9 Charging Port Original', 'SP-IP12.8CHP', 0),
  Item('iPad 12.9 Gen 5 Battery Original', 'SP-IP12.9B5', 0),
  Item('iPad 2 LCD Original', 'SS-iP8', 0),
  Item('iPad 2 Touch Panel', 'SS-iP1', 0),
  Item('iPad 3/4 LCD Original', 'SS-iP9', 0),
  Item('iPad 3/4 Original Battery', 'SPOB-iP3/4', 0),
  Item('iPad 3/4 Touch Panel', 'SS-iP2', 0),
  Item('IPad 5 Gen/Air 1 Battery', 'SB-IP5', 0),
  Item('iPad 5 Original Charging Port', 'SP-CHiP5', 0),
  Item('iPad 5/Air 1 LCD Original', 'SS-iP10', 0),
  Item('iPad 5/Air 1 Touch Panel', 'SS-iP3', 0),
  Item('iPad 5/Air1  Original Battery', 'SP-OB1/5', 0),
  Item('iPad 6 Gen Battery Original', '', 0),
  Item('iPad 6 LCD Original', 'SS-iP11', 0),
  Item('iPad 6 Original Charging Port', 'SP-6CHP', 0),
  Item('iPad 6 Touch Panel', 'SS-iP4', 0),
  Item('iPad 7 Charging Port', '', 0),
  Item('iPad 7 Original Front Camera', 'FC-IP7', 0),
  Item('iPad 7 Screen Original', 'SP-ID7S', 0),
  Item('iPad 7/8/9 LCD Original', 'SS-iP12', 0),
  Item('iPad 7/8/9 Touch Panel', 'SS-iP5', 0),
  Item('iPad 8 Charging Port Original', 'SP-IP8CHP', 0),
  Item('iPad 9 Gen Screen Original', 'SP-IPG89S', 0),
  Item('iPad Air 1 Original Charging Port', 'iPA1-CHP', 0),
  Item('iPad Air 1 Original Housing', 'iPA1-OH', 0),
  Item('iPad Air 2 Battery Original', 'ss-bip-a2', 0),
  Item('iPad Air 2 Original Home Button', 'SP-IDA2HB', 0),
  Item('iPad Air 2 Screen Original', 'SS-iP16', 0),
  Item('iPad Air 3 Screen Original', 'SS-iP17', 0),
  Item('iPad Air 4 Original Battery', 'SP-iPA4B', 0),
  Item('iPad Air 4 Screen Original', 'SS-iP18', 0),
  Item('iPad Air 5 Gen Screen Original', 'SP-OSA5', 0),
  Item('iPad Air 6 Screen Original', 'SP-IPA6S', 0),
  Item('iPad Gen 5 Original Home Button', 'SP-ID5HB', 0),
  Item('iPad Gen 7 Original Home Button', 'SP-IPHO', 0),
  Item('iPad Mini 1 LCD Original', 'SS-iP13', 0),
  Item('iPad mini 1/2 Touch Panel', 'SS-iP6', 0),
  Item('iPad Mini 2/3 LCD Original', 'SS-iP14', 0),
  Item('iPad Mini 3 Touch Panel', 'SS-iP7', 0),
  Item('iPad Mini 4 Screen Original', 'SS-iP15', 0),
  Item('IPad Mini 5 Screen Original', 'SS-iP5M', 0),
  Item('iPad Mini 6 Original Battery', '', 0),
  Item('IPad Mini 6 Screen Original', 'SS-iPM6', 0),
  Item('iPad Pro 10.5 Battery Original', 'SP-IP10.5B', 0),
  Item('iPad Pro 10.5 Battery Original ( 1962 )', 'SP-IP10.5B', 0),
  Item('iPad Pro 10.5 Battery Original ( 1963 )', 'SP-IP10.5B', 0),
  Item('iPad Pro 10.5 Battery Original ( 1964 )', 'SP-IP10.5B', 0),
  Item('iPad Pro 10.5 Screen Original', 'SS-iP20', 0),
  Item('iPad Pro 10.5 Touch Panel Original', 'SP-IP10.5TP', 0),
  Item('iPad Pro 11 1st/2ed Gen Screen Original', 'SS-iP21', 0),
  Item('iPad Pro 11 3\'gn Original Charging Port', 'SP-iP11CP', 0),
  Item('iPad Pro 11 3th/4th Gen Screen Original', 'SP-iP3', 0),
  Item('iPad Pro 11 Back Camera Original', 'SP-ID11BC', 0),
  Item('iPad Pro 11 Battery Original', 'SP-IP11B', 0),
  Item('iPad Pro 12.9 1st Gen 2015 Screen Original', 'SS-iP22', 0),
  Item('iPad Pro 12.9 2ed Gen 2017 Screen Original', 'SS-iP23', 0),
  Item('iPad Pro 12.9 3rd/4th Gen 2018/2020 Screen Original', 'SS-iP24', 0),
  Item('iPad Pro 12.9 5th/6th Gen Screen Original', 'SS-iP25', 0),
  Item('iPad Pro 9.7 Screen Original', 'SS-iP19', 0),
  Item('Front flat', '', 0),
  Item('iPhon XR Original front flat', 'SP-ffXR', 0),
  Item('iPhone 11 Original Front Flat', 'SP-11', 0),
  Item('iPhone 11 Pro Max Original Front flat', 'SS-FF11PM', 0),
  Item('iPhone 11 Pro Original Front Flat', 'FF-11P', 0),
  Item('iPhone 12 mini Front Flat Original', 'SP-12MFF', 0),
  Item('iPhone 12 Pro Max Front Flat Original', 'SP-IP12PMFF', 0),
  Item('iPhone 12/12 Pro Original Front flat', 'SS-12FF', 0),
  Item('iPhone 13 Original Front flat', 'SP-Off13', 0),
  Item('iPhone 13 Pro Max Original Front flat', 'SP-FF13PM', 0),
  Item('iPhone 14 Plus Front Flat Original', 'SP-IP14PFF', 0),
  Item('iPhone 14 Pro Max Original Front Flat', 'SS-14PMFF', 0),
  Item('iPhone 14 Pro Original Front Flat', 'SP-14 Pro FF', 0),
  Item('iPhone 5S Front Flat Original', 'SP-IP5SFF', 0),
  Item('iPhone 6 Front Flat Original', 'SP-IP6FF', 0),
  Item('iPhone 6S Front Flat Original', 'SP-IP6SFF', 0),
  Item('iPhone 7 Original Front flat', 'SP-ff7', 0),
  Item('iPhone 7 Plus Original Front Flat', 'SP-7PFF', 0),
  Item('iPhone 8 Front Flat Original', 'SP-IP8FFO', 0),
  Item('iPhone 8 Plus Original Front Flat', 'SP-8PFF', 0),
  Item('iPhone X Original Front Flat', 'SPiPX-OFF', 0),
  Item('iPhone XS Front Flat', 'SS-FF2', 0),
  Item('iPhone XsMax Front Flat Original', 'SP-IPXSMFFO', 0),
  Item('iPhone 15 Pro Original Front Flat', '', 0),
  Item('iPhone 15 Pro max Original Front Flat', '', 0),
  Item('Housing Iphone ', '', 0),
  Item('iPhone 11 Housing', 'SS-h11', 0),
  Item('iPhone 11 Pro Housing Original', 'SS-h11P', 0),
  Item('iPhone 11 Pro Max Housing Original', 'SS-h11PM', 0),
  Item('iPhone 12 Housing Original Warranty Life Time', 'SP-iP12H', 0),
  Item('iPhone 12 Mini Housing Original warranty Lifetime', 'SP-IP12MH', 0),
  Item('iPhone 12 Pro Housing Original Warrant LifeTime', 'SS-IP12PH', 0),
  Item('iPhone 12 Pro Max Original Housing', 'SP-IP12PMH', 0),
  Item('iPhone 13 Housing Original', 'SP-IP13H', 0),
  Item('iPhone 13 Pro Housing Original', 'SP--IP13PH', 0),
  Item('iPhone 13 Pro Max  Housing Original', 'SP-IP13PMH', 0),
  Item('iPhone 14 Housing Original', 'SP-IP14H', 0),
  Item('iPhone 14 Pro Housing Original', 'SP-IP14PH', 0),
  Item('iPhone 15 Housing Original', 'SP-IP15H', 0),
  Item('iPhone 16 Housing Original', 'SP-IP16HO', 0),
  Item('iPhone 8 Plus Housing Original', 'SP-IP8PH', 0),
  Item('iPhone X Housing Original', 'SP-XOH', 0),
  Item('iPhone X original Housing', 'SP-XH', 0),
  Item('iPhone XR Original Housing', 'SPOH-iPXR', 0),
  Item('iPhone XS Housing Original', 'SP-iPXSH', 0),
  Item('iPhone XS Max Housing Original', 'SP-iPXSMH', 0),
  Item('Back glass', '', 0),
  Item('iPhone 11 Original Back Glass', 'SS-M98', 0),
  Item('iPhone 11 Pro Max Original Back Glass', 'SS-M100', 0),
  Item('iPhone 11 Pro Original Back Glass', 'SS-M99', 0),
  Item('iPhone 12 Original Back Glass', 'SS-M101', 0),
  Item('iPhone 12 Pro Max Original Back Glass', 'SS-M103', 0),
  Item('iPhone 12 Pro Original Back Glass', 'SS-M102', 0),
  Item('iPhone 13 Pro Max Original Back Glass', 'SS-M105', 0),
  Item('iPhone 13/13 Pro/13 Mini Original Back Glass', 'SS-M104', 0),
  Item('iPhone 14 Plus Back Glass', 'SP-IP14PBG', 0),
  Item('iPhone 14 Pro Max Original Back Glass', 'SS-M107', 0),
  Item('iPhone 14 Pro Original Back Glass', 'SP-IP14PBG', 0),
  Item('iPhone 14/14 Pro Original Back Glass', 'SS-M106', 0),
  Item('iPhone 15  Original Back Glass', 'SP-IP15OBC', 0),
  Item('iPhone 15 Plus Back Glass Original', 'SP-IP15PBG', 0),
  Item('iPhone 15 Pro Max Original Back Glass', 'SP-15PMBG', 0),
  Item('iPhone 15 Pro Original Back Glass', 'SP-IP15PBG', 0),
  Item('iPhone 16 Back Glass Original', 'SP-IP16BG', 0),
  Item('iPhone 16 Pro Back Glass Original', 'SP-IP16PBB', 0),
  Item('iPhone 16 Pro Max Original Back Glass', 'SPBG-16PM', 0),
  Item('iPhone 8/8 Plus Original Back Glass', 'SS-M93', 0),
  Item('iPhone SE "2nd Generation Original Back Glass', 'SS-M108', 0),
  Item('iPhone X Original Back Glass', 'SS-M94', 0),
  Item('iPhone XR Original Back Glass', 'SS-M95', 0),
  Item('iPhone XS Original Back Glass', 'SS-M96', 0),
  Item('iPhone XSMax Original Back Glass', 'SS-M97', 0),
  Item('face ID', '', 0),
  Item('Hardware:iPhone X Face ID Issue (Hardware)', 'HW-F1', 0),
  Item('Hardware:iPhone 12 Pro Max Face ID Issue (Hardware)', 'HW-F10', 0),
  Item('Hardware:iPhone 13 Face ID Issue (Hardware)', 'HW-F11', 0),
  Item('Hardware:iPhone 13 Pro Face ID Issue (Hardware)', 'HW-F12', 0),
  Item('Hardware:iPhone 13 Pro Max Face ID Issue (Hardware)', 'HW-F13', 0),
  Item('Hardware:iPhone XS Face ID Issue (Hardware)', 'HW-F2', 0),
  Item('Hardware:iPhone XS Max Face ID Issue (Hardware)', 'HW-F3', 0),
  Item('iPhone 11 Face ID Issue (Hardware)', 'HW-F5', 0),
  Item('Hardware:iPhone XR Face ID Issue (Hardware)', 'HW-F5', 0),
  Item('Hardware:iPhone 11 Pro Face ID Issue (Hardware)', 'HW-F6', 0),
  Item('Hardware:iPhone 11 Pro Max Face ID Issue (Hardware)', 'HW-F7', 0),
  Item('Hardware:iPhone 12 Face ID Issue (Hardware)', 'HW-F8', 0),
  Item('Hardware:iPhone 12 Pro Face ID Issue (Hardware)', 'HW-F9', 0),
  Item('iPhone 12 Mini Face ID Original', 'SP-IP12MFI', 0),
  Item('iPhone 14 Pro Max Typeface Original', 'SP-IP14P', 0),
  Item('iPhone 11 Pro Max Face ID Iss', '', 0),
  Item('vibration', '', 0),
  Item('iPhone 12 Pro Max Vibration Original', 'SP-IP12PMV', 0),
  Item('iPhone 12 Vibration Original', 'SP-IP12V', 0),
  Item('iPhone 13 Pro Max Vibration Original', 'SP-IP13PMV', 0),
  Item('iPhone 13 Pro Vibration Original', 'SP-IP13PV', 0),
  Item('iPhone 13 Vibration Original', 'SP-IP13V', 0),
  Item('iPhone 14 Plus Vibration Original', 'SP-14PV', 0),
  Item('iPhone 6S Plus Original Vibration', 'SP-IP6SPV', 0),
  Item('iPhone X Vibration Original', 'SP-IPXV', 0),
  Item('iPhone XS MAX Vibration Original', 'SP-IPXSV', 0),
  Item('Samsung S21 Vibration Original', 'SP-SS21V', 0),
  Item('Home Button', '', 0),
  Item('iPhone 5S Home Button Original', 'SP-IP5SHB', 0),
  Item('iPhone 6 Flat Home Button Original', 'SP-IP6FH', 0),
  Item('iPhone 6 Home Button Original', 'SS-M105', 0),
  Item('iPhone 6 Plus Home Button Original', 'SS-M106', 0),
  Item('iPhone 6S Home Button Original', 'SS-M107', 0),
  Item('iPhone 6S Plus Home Button Original', 'SS-M108', 0),
  Item('iPhone 7 Home Button Original', 'SS-M110', 0),
  Item('iPhone 7 Plus Home Button Original', 'SS-M111', 0),
  Item('iPhone 8 Home Button Original', 'SS-M112', 0),
  Item('iPhone 8 Plus Home Button Original', 'SS-M113', 0),
  Item('iPhone SE "1st Gen" Home Button Original', 'SS-M115', 0),
  Item('iPhone SE "2nd Gen" Home Button Original', 'SS-M114', 0),
  Item('flat flash ', '', 0),
  Item('iPhone 11 Pro Max Flat Flash Original', 'SP-IP11PMFF', 0),
  Item('iPhone 12 Pro Flat Flash Original', 'SP-IP12PFF', 0),
  Item('iPhone 13 Flat Flash Original', 'SP-IP13FF', 0),
  Item('iPhone 13 Pro Flat flash Original', 'SP-IP13PFF', 0),
  Item('iPhone 13 Pro Max Flat Flash Original', 'SP-13PMFF', 0),
  Item('iPhone 14  Flat Flash Original', 'SP-14ff', 0),
  Item('iPhone 14 Plus Flat Flash Original', 'SP-IP14PFF', 0),
  Item('iPhone 14 Pro Flat Flash Original', 'SP-IP14PFF', 0),
  Item('iPhone 15 Pro Flat Flash Original', 'SP-IP15PFF', 0),
  Item('iPhone 15 Pro Max Flat Flash Original', 'SP-IP15PMFF', 0),
  Item('iPhone 16 Pro Flat Flash Original', 'SP-IPH16PFFO', 0),
  Item('iPhone  11 Pro Flat Flash Original', '', 0),
  Item('power flat ', '', 0),
  Item('iPhone 11 Power Flat Original', 'SP-IP11PF', 0),
  Item('iPhone 12 Pro Max Power Flat Original', 'SP-IP12PMPF', 0),
  Item('iPhone 13 Power Flat Original', 'SP-IP13PF', 0),
  Item('iPhone 13 Pro Max Power Flat Original', 'SP-IP13PMPF', 0),
  Item('iPhone 13 Pro Original Power Flat', 'SP-IP13PPF', 0),
  Item('iPhone 14 Power Flat Original', 'SP-IP14PF', 0),
  Item('iPhone 14 Pro  Power Flat Original', 'SP-IP14PPF', 0),
  Item('iPhone 14 Pro Max Power Flat Original', 'SP-IP14PMPF', 0),
  Item('iPhone 15 pro Power Flat Original', 'SP-IP15PF', 0),
  Item('iPhone 6 Original Power flat', 'SP-PF', 0),
  Item('iPhone 6 Plus Power Flat Original', 'SP-IP6PPF', 0),
  Item('iPhone XR Power Flat Original', 'SP-IPXRPF', 0),
  Item('iPhone 16 pro  Power Flat Original', '', 0),
  Item('Samsung', '', 0),
  Item('Samsung A04S Original Screen', 'SP-OSS04S', 0),
  Item('Samsung A14 4G Charging Port', 'SP-A14CH', 0),
  Item('Samsung A21S original Screen', 'SP-A21SOS', 0),
  Item('Samsung A22 Back Glass Original', 'SP-S22BG', 0),
  Item('Samsung A23 Original Screen', '', 0),
  Item('Samsung A25 Original Screen', 'SP-SA25S', 0),
  Item('Samsung A32 Original Screen', 'SP-A332OS', 0),
  Item('Samsung A52 Original Back Glass', 'SP-A52BG', 0),
  Item('Samsung A52 Original Screen', 'SP-SOSA52', 0),
  Item('Samsung A70 Original Charging Port', 'SP-S70CP', 0),
  Item('Samsung A70 Screen Original', 'Sp-SA70S', 0),
  Item('Samsung A72 Converter flat', 'A72-CONSUM', 0),
  Item('Samsung A72 Original Screen', 'SP-S72S', 0),
  Item('Samsung A74 Screen Original', 'SP-SA74S', 0),
  Item('Samsung B130 Original Battery', 'SP-SB130B', 0),
  Item('Samsung Fe23 Charging Port Original', 'SP-SF23CHP', 0),
  Item('Samsung Galaxy J7 Prime Screen Original', 'SP-SGJ7PS', 0),
  Item('Samsung Galaxy S24 Screen Original', 'SP-SGS24S', 0),
  Item('Samsung Galaxy Tab A 10.1 Original Screen', 'SPSUMGL-TABOS', 0),
  Item('Samsung Hard Desk 1TB Evo Original', 'SP-SHD', 0),
  Item('Samsung Laptop Battery', 'SP-BS', 0),
  Item('Samsung M12 Screen Original', 'SP-SM12S', 0),
  Item('Samsung Note 10 Plus Back Glass Original', 'SP-SN10PBG', 0),
  Item('Samsung Note 10 Plus Battery Original', 'SP-SN10PB', 0),
  Item('Samsung Note 10 Plus Screen Original', 'SP-SN10PS', 0),
  Item('Samsung Note 20 Original Battery', 'SP-SN20B', 0),
  Item('Samsung Note 20 Screen Original', 'SP-SN20S', 0),
  Item('Samsung Note 20 Ultra Original Back Glass', 'SP-SN20BG', 0),
  Item('Samsung Note 20 ULTRA Original Battery', 'SAMN20-SPOB', 0),
  Item('Samsung Note 20 Ultra Original Screen', 'SP-SN20U', 0),
  Item('Samsung S20 Back Glass Original', 'SP-SS20BG', 0),
  Item('Samsung S20 Battery Original', 'SP-SS20B', 0),
  Item('Samsung S20 FE Original Battery', 'SP-S20FEB', 0),
  Item('Samsung S20 Plus Battery Original', 'SP-SS20PB', 0),
  Item('Samsung S20 Plus Screen Original', 'SP-S20PS', 0),
  Item('Samsung S20 Screen Original', 'SP-SS20S', 0),
  Item('Samsung S20 Sim Card Original', 'SP-S20SC', 0),
  Item('Samsung S20 Ultra Original Back Glass', 'SS20-BG', 0),
  Item('Samsung S20 Ultra Original Screen', 'SS-S20', 0),
  Item('Samsung S21 Fe Back Glass Original', 'SP-SMS21FEBG', 0),
  Item('Samsung S21 Original Battery', 'SP-S21B', 0),
  Item('Samsung S21 Plus Back Glass Original', 'SP-S21PBG', 0),
  Item('Samsung S21 Plus Battery Original', 'SP-S21PB', 0),
  Item('Samsung S21 Plus Screen Original', 'SP-SS21P', 0),
  Item('Samsung S21 Ultra Back Camera Original', 'SP-SS21BC', 0),
  Item('Samsung S21 Ultra Back Glass Original', 'SP-SS21UBG', 0),
  Item('Samsung S21 Ultra Battery Original', 'SP-S21UB', 0),
  Item('Samsung S21 Ultra Charging Port Original', 'SP-S21UCHP', 0),
  Item('Samsung S21 Ultra original Back Camera', 'SP-S21BC', 0),
  Item('Samsung S21 Vibration Original', 'SP-SS21V', 0),
  Item('Samsung S21Ultra Original Screen', 'SP-SS21', 0),
  Item('Samsung S22 Battery Original', 'SP-SS22B', 0),
  Item('Samsung S22 Ultra Original Back Glass', 'SP-S22UBG', 0),
  Item('Samsung S22 ULTRA Original Battery Original', 'SP-SS22U', 0),
  Item('Samsung S22 ULTRA Original Screen', 'SP-S22US', 0),
  Item('Samsung S23 Ultra Battery Original', 'SP-SS23U', 0),
  Item('Samsung S23 Ultra Charging Port Original', 'SP-SS23UCHP', 0),
  Item('Samsung S23 Ultra Original Back Glass', 'SP-SS23BG', 0),
  Item('Samsung S23 ULTRA Original Screen', 'SP-S23OS', 0),
  Item('Apple Watch ', '', 0),
  Item('Apple Watch SE6 Housing Original', 'SP-AWSE6H', 0),
  Item('Apple Watch Series 1 Battery', '', 0),
  Item('Apple Watch Series 6 Original Back Glass', 'AWS6-BG', 0),
  Item('APPLE WATCH Series 7/8 Battery Original', 'SP-APWS78B', 0),
  Item('APPLE WATCH Serise 3/4 Front Glass', 'SS-AW1', 0),
  Item('APPLE WATCH Serise 3/4 Screen Original', 'SS-AW3', 0),
  Item('APPLE WATCH Serise 4/SE/5/6/ Battery', 'SP-APS4/5/6/SEB', 0),
  Item('APPLE WATCH Serise 7/8 Screen Original', 'SS-AW5', 0),
  Item('APPLE WATCH Serise 7/8/9 Front Glass', 'SP-AWFG789', 0),
  Item('APPLE WATCH Serise SE/5/6 Screen Original', 'SS-AW4', 0),
  Item('APPLE WATCH Serise SE/5/6/ Front Glass', 'SS-AW2', 0),
  Item('APPLE WATCH Serise Ultra 1 Screen Original', 'SP-AWU1S', 0),
  Item('Apple Watch Ultra 2 Original Back Glass', 'SP-AWU2BG', 0),
  Item('front camera', '', 0),
  Item('iPhone 12/12 Pro Original Front Camera', 'SP-FC12/12P', 0),
  Item('iPhone 11 Pro Max Front Camera Original', 'SP-IP11PMFC', 0),
  Item('iPhone 13 Pro Front Camera Original', 'SP-IP13PFC', 0),
  Item('iPhone 14 Pro Front Camera Original', 'SP-IP14PFC', 0),
  Item('iPhone 15 Original Front Camera', 'SP-IP15FC', 0),
  Item('iPhone 15 Pro Max Front Camera Original', 'SP-IP15PMFC', 0),
  Item('iPhone 7 Original Front Camera', 'SP-IP7FC', 0),
  Item('iPhone 8 Original Front Camera', 'SP-IP8FC', 0),
  Item('iPhone 8 plus Original Front Camera', 'SP-IP8PFC', 0),
  Item('iPhone X Front Camera Original', 'SP-IPFC', 0),
  Item('iPhone xr Original Front Camera', 'SP-IPXRFC', 0),
  Item('iPhone 12 Pro Max Original Front Camera', 'SS-FC12PM', 0),
  Item('iPhone 11 Pro Original Front Camera', 'SS-M115', 0),
  Item('iPhone 7 Plus Original Front Camera', 'SSFC-7P', 0),
  Item('iPhone 6s Plus Original Front Camera', 'SSFC-FC', 0),
  Item('iPhone 16 Pro Max Front Camera Original', '', 0),
  Item('Spare parts:laptop battery F3YGT', '', 0),
  Item('analog ', '', 0),
  Item('11 , Xr Screen Protector', 'AC0001xr', 1),
  Item('11 , Xr Screen Protector Privacy', 'IP11MSP', 6),
  Item('12 , 12 Pro Screen Protector', 'AC000112', 4),
  Item('12 Pro Max Screen Protector', 'AC000112pm', 4),
  Item('12 Pro Max Screen Protector Privacy', '12PMSP', 7),
  Item('13 Pro Max Screen Protector', 'AC000113pm', 2),
  Item('14 Pro Max Screen Protector', 'AC000114pm', 1),
  Item('iPhone 11 Pro/ 12 Pro Back Camera Lens Screen Protector', 'AC00012PBCSP', 0),
  Item('iPhone 11/ 11 Pro Max Back Camera Lens Screen Protector', 'AC00011PMCL', 0),
  Item('iPhone 12 Mini Screen Protector', 'AC-000012M', 0),
  Item('iPhone 12 Pro Max Back Camera Lens Screen Protector', 'AC00012PMCL', 0),
  Item('iPhone 12/12 Pro Screen Protector Privacy', 'AC-12PSPP', 5),
  Item('iPhone 13 , 13 Pro ,14 Screen Protector', 'AC000113', 7),
  Item('iPhone 13 , 13 Pro ,14 Screen Protector Privacy', 'ACC-SCPIP13', 4),
  Item('iPhone 13 Mini Screen Protector', 'ACC-IP13MSC', 0),
  Item('iPhone 13/13 Mini Pro Back Camera Lens Screen Protector', 'AC00013BCSP', 0),
  Item('iPhone 14 Pro Back Camera Lens Screen Protector', 'AC00014PCL', 0),
  Item('iPhone 14 Pro Screen Protector', 'AC000114p', 5),
  Item('iPhone 15 , 15 Pro Screen Protector', 'AC-15SP', 12),
  Item('iPhone 15 Plus Screen Protector', 'ACC00015P', 0),
  Item('iPhone 15 Pro Max Screen Protector', 'AC00015PM', 1),
  Item('iPhone 15 Pro Max Screen Protector Privacy', 'ACC-IP15PMSP', 0),
  Item('iPhone 15/15 Pro/15 Plus Back Camera Lens Screen Protector', 'AC00015/15PCL', 0),
  Item('iPhone 16 Pro Max Screen Protector', 'AC00016PM', 7),
  Item('iPhone 16 Pro Max Screen Protector Privacy', 'ACC-IP16PSP', 3),
  Item('iPhone 16 Pro Screen Protector', 'AC00016P', 13),
  Item('iPhone 16 Pro Screen Protector Privacy', 'ACC-IP16PSP', 11),
  Item('iPhone 16 Screen Protector', 'AC00016', 6),
  Item('iPhone 17 Pro Max Screen Protector', 'ACC-IP17PMSP', 9),
  Item('iPhone 17 Pro Max Screen Protector Privacy', 'ACC-IP17PMSP', 2),
  Item('iPhone 17 Pro Screen protector', 'ACC-IP17OSP', 9),
  Item('iPhone 17 Pro Screen Protector Privacy', 'ACC-IP17PSCPP', 5),
  Item('iPhone 17 Screen protector', 'ACC-IP17S', 6),
  Item('iPhone 17 Screen Protector Privacy', 'ACC-IP17SPP', 0),
  Item('iPhone14 Pro Max Screen Protector Privacy', 'ACC-IP14PSP', 2),
  Item('iPhone15/15 Pro Screen Protector Privacy', 'ACC-IP15PSP', 7),
  Item('X , Xs , 11 Pro Screen Protector', 'AC0001x', 15),
  Item('X , Xs , 11 Pro Screen Protector Privacy', 'ACC-IPXSPP', 6),
  Item('Xs Max , 11 Pro Max Screen Protector', 'AC0001xsm', 5),
  Item('Xs Max , 11 Pro Max Screen Protector Privacy', 'ACC-IPXSMSP', 3),
  Item('camera lens protector ', '', 0),
  Item('iPhone 11 Camera Lens Protector - 9H', 'AC00029h11', 0),
  Item('iPhone 11 Camera Lens Protector - S+', 'AC00029h11', 0),
  Item('iPhone 11 Pro Camera Lens Protector - 9H', 'AC00029h11p', 0),
  Item('iPhone 11 Pro Camera Lens Protector - S+', 'AC0002sp11p', 0),
  Item('iPhone 11 Pro Max Camera Lens Protector - 9H', 'AC00029h11pm', 0),
  Item('iPhone 11 Pro Max Camera Lens Protector - S+', 'AC0002sp11pm', 0),
  Item('iPhone 12 Camera Lens Protector - 9H', 'AC00029h12', 0),
  Item('iPhone 12 Camera Lens Protector - S+', 'AC0002sp12', 0),
  Item('iPhone 12 Pro Camera Lens Protector - 9H', 'AC00029h12p', 0),
  Item('iPhone 12 Pro Camera Lens Protector - S+', 'AC0002sp12p', 0),
  Item('iPhone 12 Pro Max Camera Lens Protector - 9H', 'AC00029h12pm', 3),
  Item('iPhone 12 Pro Max Camera Lens Protector - S+', 'AC0002sp12pm', 0),
  Item('iPhone 13 Camera Lens Protector - 9H', 'AC00029h13', 1),
  Item('iPhone 13 Camera Lens Protector - S+', 'AC0002sp13', 0),
  Item('iPhone 13 Pro Camera Lens Protector - S+', 'AC0002sp13p', 0),
  Item('iPhone 13 Pro Max Camera Lens Protector - Joyroom', 'AC0002jr13pm', 0),
  Item('iPhone 13 Pro Max Camera Lens Protector - S+', 'AC0002sp13pm', 0),
  Item('iPhone 14 Camera Lens Protector - 9H', 'AC00029h14', 2),
  Item('iPhone 14 Camera Lens Protector - S+', 'AC0002p14', 0),
  Item('iPhone 14 Pro Camera Lens Protector - Joyroom', 'AC0002jr14p', 0),
  Item('iPhone 14 Pro Camera Lens Protector - S+', 'AC0002sp14p', 0),
  Item('iPhone 14 Pro Max Camera Lens Protector - Joyroom', 'AC0002jr14pm', 0),
  Item('iPhone 14 Pro Max Camera Lens Protector - S+', 'AC0002sp14pm', 1),
  Item('iPhone 14 Pro/14 Pro Max Camera Lens Protector - 9H', 'AC00029h14pm', 0),
  Item('iPhone13 Pro/13 Pro Max Camera Lens Protector - 9H', 'AC00029h13pm', 0),
  Item('Lito iPhone 15 Pro Max Camera Glass Protector', 'AC-15PML', 0),
  Item('iPhone 16/16plus Camera Lens Protector - s+', '', 0),
  Item('iPhone 15 pro max/ 15 pro Camera Lens Protector - s+', '', 0),
  Item('Screen protector Apple watch', '', 0),
  Item('Apple Watch 38mm Screen Protector', 'AC0001aw38', 3),
  Item('Apple Watch 40mm Screen Protector', 'AC0001aw40', 0),
  Item('Apple Watch 41mm Screen Protector', 'AC0001aw41', 0),
  Item('Apple Watch 42mm Screen Protector', 'AC0001aw42', 0),
  Item('Apple Watch 44mm Screen Protector', 'AC0001aw44', 0),
  Item('Apple Watch 45mm Screen Protector', 'AC0001aw45', 0),
  Item('Apple Watch 49mm Screen Protector', 'AC0001aw49', 1),
  Item('Silicon Cover', '', 0),
  Item('Silicon Cover - iPhone 11', 'AC0003sci11', 1),
  Item('Silicon Cover - iPhone 11 Pro', 'AC0003sci11P', 2),
  Item('Silicon Cover - iPhone 11 Pro Max', 'AC-0000sci11pm', 1),
  Item('Silicon Cover - iPhone 12 /12 Pro', 'AC0003sci12', 0),
  Item('Silicon Cover - iPhone 12 Pro Max', 'Ac0000sci12pm', 4),
  Item('Silicon Cover - iPhone 13', 'AC0003sci13', 0),
  Item('Silicon Cover - iPhone 13 Pro', 'AC0000sci13p', 2),
  Item('Silicon Cover - iPhone 13 Pro Max', 'AC0000sci13pm', 2),
  Item('Silicon Cover - iPhone 14', 'AC0003sci14', 0),
  Item('Silicon Cover - iPhone 14 Plus', 'AC-000014PSC', 0),
  Item('Silicon Cover - iPhone 14 Pro', 'AC0000sci14p', 4),
  Item('Silicon Cover - iPhone 14 Pro Max', 'AC00sci14pm', 5),
  Item('Silicon Cover - iPhone 15', 'AC000SC15', 2),
  Item('Silicon Cover - iPhone 15 Pro', 'AC0000sci15p', 3),
  Item('Silicon Cover - iPhone 15 Pro Max', 'AC0000sci15pm', 2),
  Item('Silicon Cover - iPhone 16', 'AC0000sci16', 1),
  Item('Silicon Cover - iPhone 16 Pro', 'AC0000isc16p', 1),
  Item('Silicon Cover - iPhone 16 Pro Max', 'AC0000sci16pm', 1),
  Item('Silicon Cover - iPhone 7/8', 'AC000SC7/8', 2),
  Item('Silicon Cover - iPhone 7/8 Plus', 'AC000sc7/8', 2),
  Item('Silicon Cover - iPhone X / Xs', 'AC0003sciX-xs', 2),
  Item('Silicon Cover - iPhone XR', 'AC000SCXR', 3),
  Item('Silicon Cover - iPhone Xs Max', 'AC0003sciXsm', 4),
  Item('MagSafe Cover', '', 0),
  Item('MagSafe Cover - iPhone 11', 'AC0003ms11', 1),
  Item('MagSafe Cover - iPhone 11 Pro', 'AC0003ms11p', 1),
  Item('MagSafe Cover - iPhone 11 Pro Max', 'AC0003ms11pm', 2),
  Item('MagSafe Cover - iPhone 12 /12 Pro', 'AC0003ms12', 1),
  Item('MagSafe Cover - iPhone 12 Pro Max', 'AC0003ms12pm', 0),
  Item('MagSafe Cover - iPhone 13', 'AC0003lci13', 0),
  Item('MagSafe Cover - iPhone 13 Pro', 'AC0003ms13p', 0),
  Item('MagSafe Cover - iPhone 13 Pro Max', 'AC0003ms13pm', 0),
  Item('MagSafe Cover - iPhone 14', 'AC0003ms14', 0),
  Item('MagSafe Cover - iPhone 14 Pro', 'AC0003ms14p', 1),
  Item('MagSafe Cover - iPhone 14 Pro Max', 'AC0003ms14pm', 2),
  Item('MagSafe Cover - iPhone 14 plus', '', 0),
  Item('MagSafe Cover - iPhone 15', 'AC0003ms15', 1),
  Item('MagSafe Cover - iPhone 15 Plus', 'AC000MG15P', 0),
  Item('MagSafe Cover - iPhone 15 Pro', 'AC0003ms15p', 0),
  Item('MagSafe Cover - iPhone 15 Pro Max', 'AC0003ms15pm', 2),
  Item('MagSafe Cover - iPhone 16', 'AC0003ms16', 3),
  Item('MagSafe Cover - iPhone 16 Pro', 'AC0003ms16P', 3),
  Item('MagSafe Cover - iPhone 16 Pro Max', 'AC0003ms16PM', 2),
  Item('MagSafe Cover - iPhone 17', '', 0),
  Item('MagSafe Cover - iPhone 17 Pro', '', 0),
  Item('MagSafe Cover - iPhone 17 Pro Max', '', 0),
  Item('Magic Mask Cover', '', 0),
  Item('Magic Mask Cover - iPhone 11', 'AC0003mmi11', 0),
  Item('Magic Mask Cover - iPhone 11 Pro', 'AC0003mmi11p', 0),
  Item('Magic Mask Cover - iPhone 11 Pro Max', 'AC0003mmi11pm', 0),
  Item('Magic Mask Cover - iPhone 12 / 12 Pro', 'AC0003mmi12p', 0),
  Item('Magic Mask Cover - iPhone 12 Pro Max', 'AC0003mmi12pm', 0),
  Item('Magic Mask Cover - iPhone 13', 'AC0003mmi13', 0),
  Item('Magic Mask Cover - iPhone 13 Pro', 'AC0003mmi13p', 0),
  Item('Magic Mask Cover - iPhone 13 Pro Max', 'AC0003mmi13pm', 0),
  Item('Magic Mask Cover - iPhone 14', 'AC0003mmi14', 0),
  Item('Magic Mask Cover - iPhone 14 Pro', 'AC0003mmi14p', 0),
  Item('Magic Mask Cover - iPhone 14 Pro Max', 'AC0003mmi14pm', 0),
  Item('MagSafe Cover - iPhone 16 Pro Max', '', 0),
  Item('Magic Mask Cover - iPhone 15', '', 0),
  Item('Magic Mask Cover - iPhone 15 Pro', '', 0),
  Item('Magic Mask Cover - iPhone 15 Pro Max', '', 0),
  Item('Magic Mask Cover - iPhone 16', '', 0),
  Item('Magic Mask Cover - iPhone 16 Pro Max', '', 0),
  Item('Magic Mask Cover - iPhone 17 Pro', '', 0),
  Item('Leather Cover', '', 0),
  Item('Leather Cover - iPhone 11', 'AC0003lci11', 0),
  Item('Leather Cover - iPhone 11 Pro', 'AC0003lci11p', 0),
  Item('Leather Cover - iPhone 11 Pro Max', 'AC0003lci11pm', 0),
  Item('Leather Cover - iPhone 12 /12 Pro', 'AC0003lci12', 0),
  Item('Leather Cover - iPhone 12 Pro Max', 'AC0003lci12pm', 0),
  Item('Leather Cover - iPhone 13', 'AC0003lci13', 0),
  Item('Leather Cover - iPhone 13 Pro', 'AC0003lci13p', 0),
  Item('Leather Cover - iPhone 13 Pro Max', 'AC0003lci13pm', 0),
  Item('Leather Cover - iPhone 14', 'AC0003lci14', 0),
  Item('Leather Cover - iPhone 14 Pro', 'AC0003lci14p', 0),
  Item('Leather Cover - iPhone 14 Pro Max', 'AC0003lci14pm', 0),
  Item('King Kong Cover', '', 0),
  Item('King Kong cover 6 / 6s plus', 'ACC-KKC', 0),
  Item('King Kong Cover iPhone 7 Plus', 'ACC-7PC', 0),
  Item('King Kong iPhone 7 /8 - Transparent Cover', 'AC0003kki7-8', 0),
  Item('King Kong Transparent Cover - iPhone 11', 'AC0003kki11', 0),
  Item('King Kong Transparent Cover - iPhone 11 Pro', 'AC0003kki11p', 0),
  Item('King Kong Transparent Cover - iPhone 11 Pro Max', 'AC0003kki11pm', 0),
  Item('King Kong Transparent Cover - iPhone 12', 'AC0003kki12', 0),
  Item('King Kong Transparent Cover - iPhone 12 Pro', 'AC0003kki12p', 0),
  Item('King Kong Transparent Cover - iPhone 12 Pro Max', 'AC0003kki12pm', 0),
  Item('King Kong Transparent Cover - iPhone 13', 'AC0003kki13', 0),
  Item('King Kong Transparent Cover - iPhone 13 Pro Max', 'AC0003kki13pm', 0),
  Item('King Kong Transparent Cover - iPhone 14', 'AC0003kki14', 0),
  Item('King Kong Transparent Cover - iPhone 14 Pro', 'AC0003kki14p', 0),
  Item('King Kong Transparent Cover - iPhone 14 Pro Max', 'AC0003kki14pm', 0),
  Item('King Kong Transparent Cover - iPhone X/Xs', 'AC0003kkiXs', 0),
  Item('King Kong Transparent Cover - iPhone Xr', 'AC0003G4iXr', 0),
  Item('King Kong Transparent Cover - iPhone Xs Max', 'AC0003kkiXsm', 0),
  Item('Gear4 Cover', '', 0),
  Item('Gear4 iPhone 11 - Transparent Cover', 'AC0003G4i11', 0),
  Item('Gear4 iPhone 11 Pro - Transparent Cover', 'AC0003G4i11p', 2),
  Item('Gear4 iPhone 11 Pro Max - Transparent Cover', 'AC0003G4i11pm', 1),
  Item('Gear4 iPhone 12 Pro Max - Transparent Cover', 'AC0003G4i12pm', 1),
  Item('Gear4 iPhone 12/12 Pro - Transparent Cover', 'AC03G4i12', 2),
  Item('Gear4 iPhone 13 - Transparent Cover', 'AC0003G4i13', 0),
  Item('Gear4 iPhone 13 Pro - Transparent Cover', 'AC0003G4i13p', 0),
  Item('Gear4 iPhone 13 Pro Max - Transparent Cover', 'AC0003G4i13pm', 2),
  Item('Gear4 iPhone 14 - Transparent Cover', 'AC0003G4i14', 0),
  Item('Gear4 iPhone 14 Pro - Transparent Cover', 'AC0003G4i14p', 3),
  Item('Gear4 iPhone 14 Pro Max - Transparent Cover', 'AC0003G4i14pm', 1),
  Item('Gear4 iPhone 15 - Transparent Cover', 'AC0003G4i15', 0),
  Item('Gear4 iPhone 15 Pro - Transparent Cover', 'AC-15PG4', 2),
  Item('Gear4 iPhone 15 Pro Max - Transparent Cover', 'AC-15PMG4', 3),
  Item('Gear4 iPhone 16 - Transparent Cover', 'ACC-IP16G4', 0),
  Item('Gear4 iPhone 16 Pro - Transparent Cover', 'ACC-IP16PG4', 1),
  Item('Gear4 iPhone 16 Pro Max - Transparent Cover', 'ACC-I16PMG4', 0),
  Item('Gear4 iPhone X/Xs - Transparent Cover', 'AC0003G4iX', 0),
  Item('Gear4 iPhone Xs Max - Transparent Cover', 'AC0003G4iXsm', 0),
  Item('Magic Mask With Frame', '', 0),
  Item('iPhone 11  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP11MMCC', 1),
  Item('iPhone 11 Pro  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP11PMMMCC', 0),
  Item('iPhone 11 Pro Max Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP11PMMC', 2),
  Item('iPhone 12 Pro Max  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP12PPMMMMCC', 1),
  Item('iPhone 12/12 Pro  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP1212PMMMCC', 0),
  Item('iPhone 13 Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP13MMCFF', 0),
  Item('iPhone 13 Pro  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP13PMMMCCC', 0),
  Item('iPhone 13 Pro Max  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP13PMMMMCC', 0),
  Item('iPhone 14 Pro  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP14PMMMCC', 1),
  Item('iPhone 14 Pro Max Magsafe Magic Mask Clear With Frame Cover', 'ACC-IO14PPM', 0),
  Item('iPhone 15 Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP15MMCW', 0),
  Item('iPhone 15 Pro  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP15PMMMCC', 0),
  Item('iPhone 15 Pro Max Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP15PMMC', 0),
  Item('iPhone 16  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP16MMCC', 1),
  Item('iPhone 16 Pro  Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP16PMMMCC', 0),
  Item('iPhone 16 Pro Max Magsafe Magic Mask Clear With Frame Cover', 'ACC-IP16PMMMCFC', 0),
  Item('Magic Mask Colored Case', '', 0),
  Item('iPhone 11 Magic Mask Colored Cover', 'SP-IP11MGC', 0),
  Item('iPhone 11 Pro Max Magic Mask Colored Cover', 'SP-IP11PMMGC', 2),
  Item('iPhone 12 Pro Magic Mask Colored Cover', 'ACC-IP12PMMC', 2),
  Item('iPhone 12 Pro Max Magic Mask Colored Cover', 'ACC-IP12PMMMC', 2),
  Item('iPhone 13 Pro Magic Mask Colored Cover', 'ACC-IP13PMMMC', 0),
  Item('iPhone 13 Pro Max Magic Mask Colored Cover', 'ACC-IP13PMMC', 2),
  Item('iPhone 13/14 Magic Mask Colored Cover', 'ACC-IP1314MMC', 1),
  Item('iPhone 14 Pro Magic Mask Colored Cover', 'ACC-IP14PMM', 0),
  Item('iPhone 14 Pro Max Magic Mask Colored Cover', 'ACC-IP14PMMC', 2),
  Item('iPhone 15 Magic Mask Colored Cover', 'ACC-IP15MMC', 2),
  Item('iPhone 15 Pro Magic Mask Colored Cover', 'ACC-IP15PMMC', 1),
  Item('iPhone 15 Pro Max Magic Mask Colored Cover', 'ACC-IP15PMMC', 2),
  Item('iPhone 16 Magic Mask Colored Cover', 'ACC-IP16MMCC', 3),
  Item('iPhone 16 Pro Magic Mask Colored Cover', 'ACC-IP16P', 2),
  Item('iPhone 16 Pro Max Magic Mask Colored Cover', 'ACC-IP16PMG', 3),
  Item('Belkin Cover', '', 0),
  Item('iPhone 11 Belkin Cover', 'AC-11BC', 1),
  Item('iPhone 11 Pro Belkin Cover', 'ACC-IP11PBC', 0),
  Item('iPhone 11 Pro Max Belkin Cover', 'ACC-IP11PMBC', 0),
  Item('iPhone 12 Pro Max Belkin Cover', 'ACC-IP12PMBC', 0),
  Item('iPhone 12/12 Pro Belkin Cover', 'AC-12PBC', 1),
  Item('iPhone 13 Pro Belkin Cover', 'AC-13PBC', 0),
  Item('iPhone 13 Pro Max Belkin Cover', 'ACC-IP13PMBC', 1),
  Item('iPhone 13/14  Belkin Cover', 'AC-13BC', 0),
  Item('iPhone 14 Pro Belkin Cover', 'AC-14PBC', 0),
  Item('iPhone 14 Pro Max Belkin Cover', 'ACC-IP14PMBC', 1),
  Item('iPhone 15  Belkin Cover', 'AC-15BC', 0),
  Item('iPhone 15 Pro Belkin Cover', 'AC-15PBC', 1),
  Item('iPhone 15 Pro Max Belkin Cover', 'ACC-IP15PMBC', 0),
  Item('iPhone 16 Belkin Cover', 'AC-16BC', 0),
  Item('iPhone 16 Plus Belkin Cover', 'ACC-IP16PBC', 0),
  Item('iPhone 16 Pro Belkin Cover', 'AC-16PBC', 0),
  Item('iPhone 16 Pro Max Belkin Cover', 'ACC-IP16PMBC', 1),
  Item('iPhone 17 Belkin Cover', 'ACC-IP17B', 5),
  Item('iPhone 17 pro Belkin Cover', '', 5),
  Item('iPhone 17 pro max Belkin Cover', '', 5),
  Item('GUSS Cover', '', 0),
  Item('iPhone 13 Pro Max Guess Cover', 'ACC-IP13PMGC', 1),
  Item('iPhone 14 Guess Cover', 'ACC-IP1GC', 0),
  Item('iPhone 14 Pro Max Guess Cover', 'ACC-IP14PMGC', 0),
  Item('iPhone 15 Guess Cover', 'ACC-IP15GC', 2),
  Item('iPhone 15 Pro Max Guess Cover', 'ACC-IP15PMGC', 1),
  Item('iPhone 16 Guess Cover', 'ACC-IP16GC', 0),
  Item('iPhone 16 Pro Guess Cover', 'ACC-IP16PGC', 0),
  Item('iPhone 16 Pro Max Guess Cover', 'ACC-IP16PMGC', 1),
  Item('Magsafe with Camera Lens Cover', '', 0),
  Item('iPhone 13 Pro Max MagSafe Cover With Camera Lens', 'ACC-IP13PMMWCL', 0),
  Item('iPhone 14 MagSafe Cover With Camera Lens', 'ACC-IP14MCWCL', 0),
  Item('iPhone 15 MagSafe Cover With Camera Lens', 'ACC-IP15MCWC', 1),
  Item('iPhone 15 Pro  MagSafe Cover With Camera Lens', 'ACC-IP15PMCWC', 0),
  Item('iPhone 16 MagSafe Cover With Camera Lens', 'ACC-IP16MCWC', 5),
  Item('iPhone 16 Pro  MagSafe Cover With Camera Lens', 'ACC-IP16PMCWC', 2),
  Item('iPhone 16 Pro Max MagSafe Cover With Camera Lens', 'ACC-IP16PMMMCWC', 0),
  Item('DDU Luxury Protective Case', '', 0),
  Item('iPhone 11 DDU Luxury Protective Case Original', 'ACC-IP11DLPC', 0),
  Item('iPhone 13 DDU Luxury Protective Case Original', 'ACC-IP13LP', 1),
  Item('iPhone 13 Pro DDU Luxury Protective Case Original', 'ACC-IP13PLC', 0),
  Item('iPhone 13 Pro Max  DDU Luxury Protective Case Original', 'ACC-IP13PRML', 1),
  Item('iPhone 14 Pro Max  DDU Luxury Protective Case Original', 'ACC-IP14PMLUPC', 1),
  Item('iPhone 15 DDU Luxury Protective Case Original', 'ACC-IP15LPC', 1),
  Item('iPhone 15 Pro Max  DDU Luxury Protective Case Original', 'ACC-IP15OMPC', 1),
  Item('iPhone 16 Pro Max DDU Luxury Protective Case Original', 'ACC-IP16PMLPC', 2),
  Item('iPhone16 DDU Luxury Protective Case Original', 'ACC-IP16L', 1),
  Item('iPhone16 Pro DDU Luxury Protective Case Original', 'ACC-IP16PLC', 0),
  Item('Magsafe Stand Cover', '', 0),
  Item('iPhone 12 Pro Max Magsafe Stand Cover Original', 'AACC-IP12PMMSC', 1),
  Item('iPhone 12/12 Pro Magsafe Stand Cover Original', 'ACC-IP1212PMSC', 0),
  Item('iPhone 13 Pro Max Magsafe Stand Cover Original', 'ACC-IP13PMMS', 0),
  Item('iPhone 13/14 Magsafe Stand Cover Original', 'ACC-IP1314MSC', 0),
  Item('iPhone 14 Pro Max Magsafe Stand Cover Original', 'ACC-IP14PMMSC', 1),
  Item('iPhone 15 Magsafe Stand Cover Original', 'ACC-IP15MSC', 1),
  Item('iPhone 15 Pro Max Magsafe Stand Cover Original', 'ACC-IP15PMM', 2),
  Item('iPhone 16 Magsafe Stand Cover Original', 'ACC-IP16MS', 1),
  Item('iPhone 16 Pro  Magsafe Stand Cover Original', 'ACC-IP16PMSC', 1),
  Item('iPhone 16 Pro Max Magsafe Stand Cover Original', 'ACC-IP16PMMS', 3),
  Item('DEVO Diamond Cover', '', 0),
  Item('DEVO Diamond Protective case  iPhone 13/14', 'ACC-IP1314DDPC', 0),
  Item('DEVO Diamond Protective Case iPhone 13 Pro Max', 'ACC-IP13PMDDPC', 0),
  Item('DEVO Diamond Protective Case iPhone 14 Pro Max', 'ACC-IP14PMDDC', 0),
  Item('DEVO Diamond Protective Case iPhone 15', 'ACC-IP15DDCKL', 0),
  Item('DEVO Diamond Protective case iPhone 15 Pro', 'ACC-IP15PDDPC', 0),
  Item('DEVO Diamond Protective Case iPhone 15 Pro Max', 'ACC-IP15PMDDP', 0),
  Item('DEVO Diamond Protective case iPhone 16', 'ACC-IP16DEDPC', 0),
  Item('DEVO Diamond Protective case iPhone 16 Pro', 'ACC-IP16PDDCPC', 0),
  Item('DEVO Diamond Protective Case iPhone 16 Pro Max', 'ACC-IP16PMDDOC', 0),
  Item('DEVO Magsafe Protective Cover', '', 0),
  Item('DEVO Diamond Protective case  iPhone 13/14', 'ACC-IP1314DDPC', 0),
  Item('DEVO Diamond Protective Case iPhone 13 Pro Max', 'ACC-IP13PMDDPC', 2),
  Item('DEVO Diamond Protective Case iPhone 14 Pro Max', 'ACC-IP14PMDDC', 1),
  Item('DEVO Diamond Protective Case iPhone 15', 'ACC-IP15DDCKL', 1),
  Item('DEVO Diamond Protective case iPhone 15 Pro', 'ACC-IP15PDDPC', 0),
  Item('DEVO Diamond Protective Case iPhone 15 Pro Max', 'ACC-IP15PMDDP', 2),
  Item('DEVO Diamond Protective case iPhone 16', 'ACC-IP16DEDPC', 2),
  Item('DEVO Diamond Protective case iPhone 16 Pro', 'ACC-IP16PDDCPC', 2),
  Item('DEVO Diamond Protective Case iPhone 16 Pro Max', 'ACC-IP16PMDDOC', 2),
  Item('DEVO iPhone 11 Magsafe Protective Case Cover Original', 'ACC-IP11PCC', 1),
  Item('DEVO iPhone 11 Pro Magsafe Protective Case Cover Original', 'ACC-IPPMPC', 2),
  Item('DEVO iPhone 11 Pro Max Magsafe Protective Case Cover Original', 'ACC-IP11PMMPC', 0),
  Item('DEVO iPhone 12 Pro Max Magsafe Protective Case Cover Original', 'ACC-IP12PMPC', 2),
  Item('DEVO iPhone 12/12 Pro Magsafe Protective Case Cover Original', 'ACC-IP1212PMP', 0),
  Item('DEVO iPhone 13 Pro Magsafe Protective Case Cover Original', 'ACC-IP13PMPCC', 0),
  Item('DEVO iPhone 13 Pro Max Magsafe Protective Case Cover Original', 'ACC-IP13PPMCC', 2),
  Item('DEVO iPhone 13/14 Magsafe Protective Case Cover Original', 'ACC-IP1314MPC', 1),
  Item('DEVO iPhone 14 Pro  Magsafe Protective Case Cover Original', 'ACC-14PMCPC', 1),
  Item('DEVO iPhone 14 Pro Max  Magsafe Protective Case Cover Original', 'ACC-IP14PPMPC', 2),
  Item('DEVO iPhone 15 Magsafe Protective Case Cover Original', 'ACC-IP15MMPCC', 1),
  Item('DEVO iPhone 15 Plus  Magsafe Protective Case Cover Original', 'ACC-IP15PMPCC', 1),
  Item('DEVO iPhone 15 Plus Magsafe Protective Case Cover Original', 'ACC-IP15PMPCC', 0),
  Item('DEVO iPhone 15 Pro Magsafe Protective Case Cover Original', 'ACC-IP15OMCP', 0),
  Item('DEVO iPhone 15 Pro Max  Magsafe Protective Case Cover Original', 'ACC-IP15PMMPC', 3),
  Item('DEVO iPhone 16 E Magsafe Protective Case Cover Original', 'ACC-IP16EMPC', 0),
  Item('DEVO iPhone 16 Magsafe protective Case Cover Original', 'ACC-IP16MPSC', 1),
  Item('DEVO iPhone 16 Plus Magsafe Protective Case Cover Original', 'ACC-IP16PMPCC', 1),
  Item('DEVO iPhone 16 Pro Magsafe Protective Case Cover Original', 'ACC-IP16PMPC', 1),
  Item('DEVO iPhone 16 Pro Max  Magsafe Protective Case Cover Original', 'AC-IP16PMMPCP', 4),
  Item('DEVO iPhone 7+/8+ Magsafe Protective Case Cover Original', 'ACC-IP8P7PMP', 2),
  Item('DEVO iPhone XR Magsafe Protective Case Cover Original', 'ACC-IPXRMPSC', 2),
  Item('DEVO iPhone XS Magsafe Protective Case Cover Original', 'ACC-IPXSMPCS', 0),
  Item('DEVO iPhone XS Max Magsafe Protective Case Cover Original', 'ACC-IPXSMPC', 1),
  Item('UNIQ Cover', '', 0),
  Item('Uniq Clario Sustainable Protective Case for iPhone 16', '', 2),
  Item('Kuchi Cover', '', 0),
  Item('iPhone 11 Pro Max Kuchi Cover', 'AC0003Kc11pm', 0),
  Item('iPhone 12 Kuchi Cover', 'AC0003Kc12', 0),
  Item('iPhone 12 Pro Kuchi Cover', 'AC0003Kc12p', 0),
  Item('iPhone 13 Pro Max Kuchi Cover', 'AC0003Kc13pm', 0),
  Item('iPhone 14 Pro Max Kuchi Cover', 'AC0003Kc14pm', 0),
  Item('Apple Watch Cover', '', 0),
  Item('Apple Watch  "38 - 40 - 41mm" Sport Band "Silicon"', 'AC0005awsmsp', 0),
  Item('Apple Watch  "42 - 44 - 45 - 49mm" Color Band', 'AC0005awlrcb', 0),
  Item('Apple Watch  "42 - 44 - 45 - 49mm" Sport Band "Silicon"', 'AC0005awlrsp', 0),
  Item('Apple Watch "38 - 40 - 41mm" Color Band', 'AC0005awsmcb', 0),
  Item('Apple Watch 33mm Cover + Band', 'AC0004aw338', 0),
  Item('Apple Watch 38mm Screen Protector', 'AC0001aw38', 0),
  Item('Apple Watch 40mm Cover + Band', 'AC0004aw440', 0),
  Item('Apple Watch 40mm Screen Protector', 'AC0001aw40', 0),
  Item('Apple Watch 41mm Cover + Band', 'AC0004aw741', 0),
  Item('Apple Watch 41mm Screen Protector', 'AC0001aw41', 0),
  Item('Apple Watch 42mm Cover + Band', 'AC0004aw342', 0),
  Item('Apple Watch 42mm Screen Protector', 'AC0001aw42', 0),
  Item('Apple Watch 44mm Cover + Band', 'AC0004aw444', 0),
  Item('Apple Watch 44mm Screen Protector', 'AC0001aw44', 0),
  Item('Apple Watch 45mm Cover + Band', 'AC0004aw745', 0),
  Item('Apple Watch 45mm Screen Protector', 'AC0001aw45', 0),
  Item('Apple Watch 49mm Screen Protector', 'AC0001aw49', 0),
  Item('Apple watch LoopMax Band42/44/45/49 mm', 'ACC-AWBLP', 0),
  Item('Apple Watch Magnatic LoopMax Band42/44/45/49 mm', 'ACC-APWMLP', 0),
  Item('Apple Watch Magnetic Charging Cable', 'AC0009awa', 0),
  Item('Apple Watch Spigen Band42/44/45/49mm', 'ACC-AWSB', 0),
  Item('Apple Watch Ultra 49mm Cover + Band', 'AC0004awu49', 0),
  Item('AirPods Cover ', '', 0),
  Item('AirPods "2nd Gen" Cover', 'AC0003ap2', 0),
  Item('AirPods "3rd Gen" Cover', 'AC0003ap3', 1),
  Item('Airpods Max  Original', 'ACC-APM', 0),
  Item('AirPods Pro ( 2nd generation ) with MagSafe Charging Case (USB‑C)', 'AC-000APMG', 0),
  Item('AirPods Pro 2 One Pice', 'AC-000AP2', 0),
  Item('AirPods Pro Cover', 'AC0003app', 0),
  Item('Anker ACC', '', 0),
  Item('Anker 3.5mm Male to Male Audio Cable 4ft, Black', 'A7123H12', 1),
  Item('Anker 312 USB-C Fast Charger 25W Warranty 18 Month', '194644126919', 0),
  Item('Anker 312 USB-C Fast Charger 30w', 'A2640L11', 0),
  Item('Anker 322 Type C to Lightning Cable 3ft Braided', 'A322TCL', 0),
  Item('Anker 322 USB-C to Lightning Cable 3ft Braided', 'A81B5H11', 0),
  Item('Anker 322 USB-C to Lightning Cable 6ft Braided', 'A81B6H11', 0),
  Item('Anker 322 USB-C To USB-C Cable', 'AC000Anker', 0),
  Item('Anker 324 Power Bank-10000mAh,12W 2Port', 'A1237H21', 0),
  Item('ANKER 336 Charger 67w Original', '[6940268892419]', 0),
  Item('Anker 4-Port Ultra Slim USB3.0 Data Hub B2C, Black', 'A7516016', 2),
  Item('Anker 544 USB-C To USB-C 240W Cable', 'A80F6P21', 0),
  Item('Anker 623 Magnetic Wireless Charger MagGo', '[6940268888023]', 0),
  Item('Anker A2620 Original Adaptor', '6283798', 0),
  Item('Anker Adapter 20W Original', 'ACC-AA20W', 0),
  Item('Anker Power Conference, Black', 'A3301H11', 0),
  Item('Anker PowerCore III Sense 10K, Black', 'A1244H12', 0),
  Item('Anker PowerLine II With Lightning Connector 3ft, White', 'A8432H22', 0),
  Item('Anker Powerline II with lightning Connector 6ft, White', 'A8433H22', 0),
  Item('ANKER PowerLine+ II Lightning to USB Cable, Red', 'A8452091', 0),
  Item('Anker Powerline+ III USB-C Cable With Lightning 24kGold', 'A8843hb1', 0),
  Item('Anker PowerPort III Nano-20W, White Iteration 2', 'A2633G22', 0),
  Item('Anker Premium 7-in-1 USB-C Hub, Gray', 'A8352HA1', 0),
  Item('Anker Sound Core C30i Original', '[194644043346]', 0),
  Item('Anker Sound core Liberty Air 2 Pro, Black', 'A3951011', 0),
  Item('Anker Sound Core Life U2i, Black', 'A3213H11', 0),
  Item('Anker Soundcore Life Note 3, White', 'A3933H21', 0),
  Item('Anker Soundcore Life Note 3i, Black', 'A3983H11', 0),
  Item('Anker Soundcore Life Note 3i, White', 'A3983H21', 0),
  Item('Anker Soundcore life P2 Mini, White', 'A3944021', 0),
  Item('Anker soundcore Life P2i, Black', 'A3991H11', 0),
  Item('Anker soundcore Life P2i, White', 'A3991H21', 0),
  Item('Anker Soundcore Life P3, Navy', 'A3939031', 0),
  Item('Anker Soundcore R50i NC', '[194644043612] [194644197421]', 0),
  Item('Anker Soundcore V20i Open-Ear Earbuds', '[194644200916]', 0),
  Item('Anker Thunderbolt 240W 3.3ft Ultra Fast Transfer And Charging Cable', 'ACC-AN240W', 0),
  Item('Anker Zolo Magnetic Power Bank, 10000mAh Wireless Stand', '[194644209674]', 0),
  Item('Anker Zolo Power Bank-10000mAh -1USB-C Port 1USB-A Port', '[194644291150]', 0),
  Item('HITCH', '', 0),
  Item('HITCH 20w lightning to USB-C Cable - 1 meter', '20wLC-1M', 0),
  Item('HITCH 20w lightning to USB-C Cable - 2 meter', '20wLC-2M', 0),
  Item('HITCH 20w Power Adapter', '20PA', 0),
  Item('HITCH 25W-5A MAGNETIC CABLE', 'H5a-25wMC', 0),
  Item('HITCH 2×1 USB-C™ CABLE – 60W PD - 1M', '2x1PD60-1', 0),
  Item('HITCH 2×1 USB-C™ CABLE – 60W PD - 2M', '2x1PD60-2', 0),
  Item('HITCH 65 GaN Charger - Compact Size, High Performance', 'H65W', 0),
  Item('HITCH Camera Cover - for Laptop - Desktop - iPad', 'HCC', 0),
  Item('HITCH Car Gravity Mobile Holder', 'Hcgmb', 0),
  Item('HITCH Fastlane - 30w PD Car Charger - Black', 'FL3', 0),
  Item('HITCH FOLDABLE MOBILE SIDE MOUNT – BLACK', 'HFMS-b', 0),
  Item('HITCH FOLDABLE MOBILE SIDE MOUNT – SILVER', 'HFMS-s', 0),
  Item('HITCH Invisible Laptop Stand - Black', 'H-ilsb', 0),
  Item('HITCH Invisible Laptop Stand - Gray', 'H-ilsg', 0),
  Item('HITCH Invisible Mobile Stand compatible with most phones Black', 'H-ims', 0),
  Item('HITCH Lightning Cable - 2.4A - 1m length', 'L2.4-1', 0),
  Item('HITCH Lightning Cable - 2.4A - 2m length', 'L2.4-2', 0),
  Item('HITCH Magnetic Cable 90° - 3A-18w Fast Charge - 1.5m length', 'MC9015', 0),
  Item('HITCH Magnetic Cable XL - 3A-18w Fast Charge - 1.5m length', 'MCXL15', 0),
  Item('HITCH Magsafe mobile stand compatible with iPhone 12 series Black', 'HMS', 0),
  Item('HITCH Micro-USB Cable - 3A-18w Fast Charge - 1m length', 'HM3118w-1M', 0),
  Item('HITCH Mini Pro HUB - 5 in 1 USB-C Multiport Adapter', 'Hhub-5n1', 0),
  Item('HITCH Power Booster - 36w - Q3.0 & PD Wall Charger - Black', 'PB36', 0),
  Item('HITCH PowerBrick 10000mAh - PD & Q3.0 Power Bank - 3A-18w Fast Charge - Black', 'HPb3a-10k', 0),
  Item('HITCH SUPER FAST CHARGE USB-C™ – SUPPORTS DASH-WARP-VOOC-SAMSUNG AFC', 'HSFC-Vooc', 0),
  Item('HITCH Thunder Cable 2 USB C to USB C - PD Magnetic Cable - Up to 5A-100w - 1m length', 'TC2-1M', 0),
  Item('HITCH Thunder Cable 2 USB C to USB C - PD Magnetic Cable - Up to 5A-100w - 2m length', 'TC2-2M', 0),
  Item('HITCH Tri—P 30w Car Charger - 3 Ports - Q3.0 + SCP Support - Black', 'TRIP3', 0),
  Item('HITCH USB-C to Lightning - 3A-18w Original C94 Chip', 'H-C-LIGHTNING18W-c94', 0),
  Item('HITCH USB-C to USB 3.0 Cable - 3A-18w Fast Charge - 1 m length', 'H3C18w-1', 0),
  Item('HITCH USB-C to USB 3.0 Cable - 3A-18w Fast Charge - 2m length', '', 0),
  Item('HITCH USB-C to USB-C Cable 3.1 Gen 2 PD - 100w / 5A - 1m length', 'CC100-1M', 0),
  Item('HITCH USB-C to USB-C Cable 3.1 Gen 2 PD - 100w / 5A - 2m length', 'CC100-2M', 0),
  Item('3 Tech', '', 0),
  Item('3Tech PD USB+C Charger 20W', '', 0),
  Item('3Tech PD USB+C Charger 20W', 'TW200', 0),
  Item('3Tech Type-C  to Type-C 65W  Cable', 'TC300', 2),
  Item('3tech USB to Lightning Weaving Cable - 3A', 'TL201', 0),
  Item('3Tech USB To Micro Weaving Cable Original', 'TM201', 4),
  Item('3tech USB to Type-C Weaving Cable - 3A', 'TT201', 4),
  Item('3tech Wall Charger Super Fast Charge 25W USB 5A', 'TW5A1', 0),
  Item('3Tech Cable Type-C to Lightening', 'TL100', 0),
  Item('Momex', '', 0),
  Item('"Elite-LinkLightning to Type-C Cable -1.2M" Silver /Black', 'DL31S/D/L', 0),
  Item('"Elite-LinkLightning to Type-C Cable -3M"', 'DL50D', 0),
  Item('"One Link4 in 1 Type C PD Cable 1.2m "Grey', 'DC12D', 0),
  Item('1-Link Flow CC 100w USB-C Braided cable 2m', 'D25D', 0),
  Item('1-Link Flow Duo 2-in-1 Braided Cable 1.5m (Black) / (White)', 'DL56D', 0),
  Item('1-Power X Power Bank 10000mAh With Built-in USB-C Cable', 'IP152W', 0),
  Item('/Accessories:1-Power Flow 10000mAh', '', 0),
  Item('1-World 35W 5-port Dual AC Travel Adapter', '', 1),
  Item('Acefast A69 PD30W GaN (USB-A+USB-C) ultra-thin charger (EU)', '6974316282709', 0),
  Item('Acefast A73  mini PD20W GaN USB-C charger (EU)', '6974316282648', 0),
  Item('Acefast C1-01 USB-C to Lightning aluminum alloy charging data cable Black', '6974316280484', 0),
  Item('Acefast C1-02 USB-A to Lightning aluminum alloy charging data cable Black', '6974316280507', 0),
  Item('C1-05 Lightning to 3.5mm aluminum alloy headphones adapter cable black', '6974316280569', 0),
  Item('C1-08 USB-C to 3.5mm aluminum alloy audio cable deep black', 'B09G3JCLWG', 0),
  Item('Choetech PD 60W USB-C to USB-C Cable, 1.2M', 'CHT-XCC-1003', 0),
  Item('Choetech T511s Qi Certified 10W Fast Wireless Charger Pad - Black', 'CHT-T511-S BK', 0),
  Item('Choetech USB-A to Micro USB Cable, White', 'CHT-AB003WHT-PE', 0),
  Item('Elite 100W USB-C USB3.2 Gen 2X2 20Gbps cable 1m', 'DC31D / L', 2),
  Item('Elite 240W USB-C USB4 40Gbps cable 1m', 'DC39D', 0),
  Item('Elite 60W USB-C Cable 1.5m', 'DC30', 3),
  Item('ELITE LINK USB-A to Lightning Cable (1.2M)', 'DLllD', 0),
  Item('Elite Link USB-A to Type-C Cable - 1.2Drak Grey', 'DTA10D', 0),
  Item('Elite Mag 100W USB-C to USB-C  Magnetic Cable (1m)', 'DC35D', 0),
  Item('Elite Mag 100W USB-C to USB-C  Magnetic Cable (2m)', 'DC36D', 0),
  Item('iPower PD 3 10000mAh battery pack (White/Black)', 'IP118W/D', 0),
  Item('iPower PD 5 20000mAh battery pack (Black) / (White)', 'IP119D / W', 0),
  Item('iPower PD mini USB-C PD External Battery Pack 10000mAh - black', 'IP73D', 0),
  Item('Momax Elite-Link-1.2M Lightning to Type-C Cable  Black', 'DL51', 0),
  Item('Momax One Plug 30W Mini USB-C Charger Original', 'UM26CN', 3),
  Item('move 30w Dual-port car charger (grey)', 'UC18E', 0),
  Item('One Link 7 in 1 mutil-function USB-C hub', 'DH17E', 0),
  Item('One Plug 20W 2-Port Mini Charger (EU) (White) / (Black)', 'UM36EUW/ D', 0),
  Item('One Plug 25W Dual Output Fast Charger (EU) (White)', 'UM56EUW', 0),
  Item('One Plug 67W 3-Port Gen Charger (UM30) (White) / (Black)', 'UM30EUD/W', 0),
  Item('Power Mini 5000mAh Built-in Foldable Liahtnina Battery Oack', 'IP130MFIW', 0),
  Item('Power Mini 5000mAh Bulit-in foldable USB-C Battery oack (Black)', 'IP130D', 0),
  Item('RavPower Cable -1.2m- USB C Cable With lightning', 'RP-CB1017"', 0),
  Item('RavPower Cable USB-A to Type-C -Black -RP-CB044', '6970651389769', 0),
  Item('RavPower Charger PD 20w-Gan5.0 RP-PC1055', '[6974740778823][6974740779103]', 0),
  Item('RavPower Power Bank 20000mAh -80w-2-Port -Power House-RP-PB054', '[6970651382616]', 0),
  Item('RAVPower RP-CB030 1m Lightning Cable Black (TPE)', 'RP-CB030', 0),
  Item('RavPower Type -C To Lightning Cable Nylon 2m RP White', 'CB1017', 0),
  Item('Sahel Stock', '', 0),
  Item('Apple Cable Type-C Original', 'ACC-APCT', 0),
  Item('Apple Lightning to Type-C Cable', 'AC0007cap/wht', 0),
  Item('Apple Original USB-C 20W Power Adpater', 'AC000620wap/wht', 0),
  Item('Apple Pencil (USB-C)', 'DE-AP', 0),
  Item('JBl Go4 Original', '12001300094/40/71/43/57/33', 0),
  Item('JBL Clip 4 - Eco Original', '[6925281967580]  [6925281967597]', 0),
  Item('jBL Junior 320BT', '[1200130015809][1200130015809]', 0),
  Item('Lexar M400, 128GB, Silver (LJDM4000128G-BNBNG)', '843367128068', 1),
  Item('Lexar M400, 64GB, Silver -LJDM400064G-BNBNG', '843367128051', 0),
  Item('logitech Video Games H390 Wired Headset, Stereo Headphones With Noise-Cancelling Microphone', '5099206030015', 0),
  Item('Porodo Blue 6 Universal Sockets Power Strip 3M', '[6849108443531]', 0),
  Item('Porodo LifeStyle Rechargeable LED Display Hair Clipper', '[6849108443975]', 0),
  Item('Q.Mag Mount5 Magnetic Wireless Charging Suction Cup Car Mount 15W', 'CM25AE', 0),
  Item('RavPower Type -C To Lightning Cable Nylon 2m RP White', 'CB1017', 0),
  Item('Samsung Galaxy Z Fold6 Slim S Pen Case', '[8806095622873] [8806095622866]  [8806095624198 - 8806095645452]', 0),
  Item('Samsung S20 Ultra Leather Cover', '', 0),
  Item('SanDisk Ultra Dual Drive GO USB Type -C 64GB', '619659177171', 0),
  Item('Sticky Grippy Suction Phone Case Mount', 'ACC-PHCRIS', 1),
  Item('Ugreen Nexode 10000mAh Two-Way Fast Charging Power Bank 20w', '(PB311)', 0),
  Item('Ugreen Nexode 3-Port PD Gan Fast Charger 140w', '(CD289)', 0),
  Item('Ugreen Portable Tire Inflator Original', '[6941876219513]', 0),
  Item('USB Flash Memory 32GB', 'TU32G', 0),
  Item('Wiwu platinum cable USB to micro 1.2m-pt03 - black', 'EG-725745177-6973218946030', 0),
  Item('World 2 35W Adapter 5-Port Dual AC Charger Original', 'UA27D', 0),
  Item('Xiaomi Power Bank 10000mAh 22.5W Lite', 'ACC-MMIXPP', 0),
  Item('iPad', '', 0),
  Item('iPad 10.2 7/8/9GEN Cover', 'AC0003ip102', 0),
  Item('iPad 10.2 7/8/9GEN Nillkin Pad Cover', 'AC0003ip102', 0),
  Item('iPad 10.2inch Screen Protector', 'AC0001ip102', 0),
  Item('iPad 10.5inch Screen Protector', 'AC0001ip105', 0),
  Item('iPad 10.9 Inch Cover', 'ACC-ID10.9C', 0),
  Item('iPad 11 2020 Cover', 'AC0003ip1120', 0),
  Item('iPad 11inch Screen Protector', 'AC0001ip11', 0),
  Item('iPad 12.9 2020 Cover', 'AC0003ip12920', 0),
  Item('iPad 12.9 Screen Protector 2015-2017', 'AC1ip129o', 0),
  Item('iPad 12.9 Screen Protector 2018-2023', 'AC0001ip129n', 0),
  Item('iPad 13 Mini Screen Protector', 'AC0001ipmn', 0),
  Item('iPad 7 Mini Cover Original', 'ACC-IPA7MC', 0),
  Item('iPad 9.7inch Screen Protector', 'AC0001ip97', 0),
  Item('iPad Air 4 Cover', 'AC0003ip4', 0),
  Item('iPad Air 4 Screen Protector', 'ACC-IPA4SP', 0),
  Item('iPad Pro 11 Nillkin Cover', 'AC-000NC', 0),
  Item('iPad Pro 11 Screen Protector', 'AC-SiPP11', 0),
  Item('Cover silicone original ', '', 0),
  Item('iPhone 16 Cover silicone original', '', 0),
  Item('iPhone 16 Pro Max Magsafe Silicon Case Original', 'ACC-IP16PMMSC', 2),
  Item('Samsung ', '', 0),
  Item('Samsung Galaxy Z Fold6 Slim S Pen Case', '[8806095622873] [8806095622866]  [8806095624198 - 8806095645452]', 0),
  Item('Samsung Galaxy Z Fold 5,6 Cover', 'AC-000ZF', 0),
  Item('Kevlar Cover', '', 0),
  Item('iPhone 17 Pro Max Kevlar Cover', 'ACC-IP17PM', 0),
  Item('ACEFAST', '', 0),
  Item('Acefast C9-03 USB-C To USB-C Charging Data Cable', 'C9-03', 6),
  Item('Ravpower', '', 0),
  Item('Ravpower Type-C Adapter 20W', '6974740775105', 1),
  Item('RavPower Type -C To Lightning Cable Nylon 2m RP White', 'CB1017', 0),
  Item('RAVPower PD Pioneer 20w Wall Charger', 'ACC-RPP20W', 0),
  Item('RavPower Charger PD 20w-Gan5.0 RP-PC1055', '[6974740778823][6974740779103]', 1),
  Item('iPhone 17air  Belkin Cover', '', 1),
];
